---
layout: post
title:  "[의학통계학방법론] Ch3. Measures of Central Tendency"
category: Study
tag: [R, SAS, blog, jekyll, Jupyter, Data, Python]
toc: true
author_profile: false
---
* this unordered seed list will be replaced by the toc
{:toc}

- 뒤로가기를 누르시면 목차로 되돌아옵니다.


# Measures of Central Tendency

## 3.1 The Arithmetic Mean


<br/>

# R 프로그램 결과

<details>
<summary>
R 접기/펼치기 버튼
</summary>
<div markdown="1">

**패키지**
<details>
<summary>
설치된 패키지 접기/펼치기 버튼
</summary>

<div markdown="1">

``` r
getwd()
```

    ## [1] "C:/Biostat"

``` r
install.packages("readxl")
install.packages('ggplot2')
install.packages("Hmisc")
install.packages("psych")
```


</div>
</details>

**엑셀파일불러오기**

``` r
library('readxl')
#모든 시트를 하나의 리스트로 불러오는 함수
read_excel_allsheets <- function(file, tibble = FALSE) {
  sheets <- readxl::excel_sheets(file)
  x <- lapply(sheets, function(X) readxl::read_excel(file, sheet = X))
  if(!tibble) x <- lapply(x, as.data.frame)
  names(x) <- sheets
  x
}
```

## 3장

**3장 연습문제 불러오기**

``` r
data_chap03 <- read_excel_allsheets("data_chap03.xls")

for (x in 1:length(data_chap03)){
  assign(paste0('ex3_',1:length(data_chap03))[x],data_chap03[x])
  }
for (x in 1:length(data_chap03)){
  assign(paste0('ex3_',1:length(data_chap03))[x],data.frame(data_chap03[x]))
  }
```

### EXAMPLE 3.1

![](/study/img/ch3/3-1.png)

``` r
#데이터셋
ex3_1
```

    ##    Length
    ## 1     3.3
    ## 2     3.5
    ## 3     3.6
    ## 4     3.6
    ## 5     3.7
    ## 6     3.8
    ## 7     3.8
    ## 8     3.8
    ## 9     3.9
    ## 10    3.9
    ## 11    3.9
    ## 12    4.0
    ## 13    4.0
    ## 14    4.0
    ## 15    4.0
    ## 16    4.1
    ## 17    4.1
    ## 18    4.1
    ## 19    4.2
    ## 20    4.2
    ## 21    4.3
    ## 22    4.3
    ## 23    4.4
    ## 24    4.5

``` r
sum_x <- sum(ex3_1$Length) ; cat('Sum of X =', sum_x)
```

    ## Sum of X = 95

``` r
n <- length(ex3_1$Length); cat('Sample Size =', n)
```

    ## Sample Size = 24

``` r
x_bar <- mean(ex3_1$Length); cat('Mean of X =', x_bar)
```

    ## Mean of X = 3.958333

$$
\begin{aligned}
\sum X_i &= 95.0 \ cm \\
n &= 24 \\
\bar{X} &= \frac{\sum X_i}{n} = \frac{95.0\ cm}{24} = 3.96\ cm 
\end{aligned}
$$

<justify>
나비의 날개 길이를 측정하기 위해 추출된 24마리의 나비들을 관측한 결과,<br/> 날개의 합은 95 cm 이며 평균은 3.96 cm 이다.
</justify>

### EXAMPLE 3.2

![](/study/img/ch3/3-2.png)

``` r
#데이터셋
ex3_2
```

    ##    exam3_2.X exam3_2.Freq
    ## 1        3.3            1
    ## 2        3.4            0
    ## 3        3.5            1
    ## 4        3.6            2
    ## 5        3.7            1
    ## 6        3.8            3
    ## 7        3.9            3
    ## 8        4.0            4
    ## 9        4.1            3
    ## 10       4.2            2
    ## 11       4.3            2
    ## 12       4.4            1
    ## 13       4.5            1

-   **가중평균 계산**

``` r
library(Hmisc) # wtd.mean 사용하기 위해
xi <- ex3_2$exam3_2.X
fi <- ex3_2$exam3_2.Freq
wm <- wtd.mean(xi, weights=fi) #가중평균
round(wm,2)
```

    ## [1] 3.96

<justify>
도수분포표에서 가중평균을 구할 때에는 각 표본에 가중을 두어 합을 구한 후 가중치의 합을 나눈다.
</justify>


``` r
sum_fixi <- sum(fi*xi) # 가중합
sum_fi <- sum(fi) #가중치 합
w_mean<-sum_fixi/sum_fi #가중평균
cat("가중합 = ",sum_fixi,"   ","가중치 합 = ",sum_fi,"   ","가중평균 = ",w_mean)
```

    ## 가중합 =  95     가중치 합 =  24     가중평균 =  3.958333

$$
\begin{aligned}
\overline X_w &= \frac {\sum_{i=1}^{n}f_i \cdot X_i} {\sum_{i=1}^{n}f_i} =  \frac{95.0 cm}{24} = 3.96
\end{aligned}
$$

<br/> <br/>

- **중위수 계산**<br/>중위수는 정렬된 자료에서 중앙에 위치한
    수이다.<br/>도수분포표에서는 R에 내장되어 있는 함수인 wtd.quantile()
    함수를 사용해서 중위수를 구할 수 있다.

``` r
x.median <- wtd.quantile(xi, weights=fi, probs=c(0,.25,.5,.75,1), type=c("i/n"))
wmed <- round(x.median,5)
wvar <- wtd.var(xi, weights=fi) # 분산
cat("wtd.quatile() 로 구한 중위수","\n","중위수 = ",wmed[3],"   분산 = ",wvar)
```

    ## wtd.quatile() 로 구한 중위수 
    ##  중위수 =  3.925    분산 =  0.08514493

<justify>
도수분포표에서 중위수를 구하기 위해서는 다음의 식을 이용하여 구한다.
</justify>

$$
\begin{aligned}
median = Lower\space \space limit \space of \space Interval + \frac{0.5n-Cummulative \space Frequency}{Num. of \space observations \space in \space interval} \cdot Interval \space size
\end{aligned}
$$

<justify>
해당 데이터를 표로 작성하면 다음과 같다.
</justify>

|$X_i(cm)$|$f_i$|$f_iX_i(cm)$|
|:---:|:---:|:---:|
|3.3|1|3.3|
|3.4|0|0|
|3.5|1|3.5|
|3.6|2|7.2|
|3.7|1|3.7
|3.8|3|11.4|
|3.9|3|11.7|
|4.0|4|16.0|
|4.1|3|12.3|
|4.2|2|8.4|
|4.3|2|8.6|
|4.4|1|4.4|
|4.5|1|4.5|
|Sum|24|95|


<justify>
1) 예상 구간의 하한값<br/>24개의 관측치 중 11개의 관측치는 4.0cm 보다 작고 9개는 크다.<br/>그러므로 통상적인 중위수는 12번째 값이 포함된 4.0 이라 하기는 어렵다.<br/>하지만 중위수는 [3.95,4.05] 이내에 있을 필요가 있다고 생각해야한다.<br/>따라서 예상구간의 하한값은 3.95 가 된다.
</justify>

<br/>

<justify>
2) 총 빈도
</justify>

``` r
sum(fi)
```

    ## [1] 24

<justify>
3) 누적 빈도<br/>누적빈도는 4.0이 오기 전 까지의 누적 빈도를 사용한다.
</justify>

``` r
which(fi==4.0) # 8번째 인덱스에 4.0 위치
```

    ## [1] 8

``` r
cf <- cumsum(fi)
cf[7] #7번째 인덱스 까지의 누적빈도
```

    ## [1] 11
<justify>
4) 구간 크기
</justify>

``` r
diff(xi) #0.1
```

    ##  [1] 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1

<justify>
 이렇게 구한 값들로 중위수를 구하면 다음과 같다.<br/>
</justify>

$$
\begin{aligned}
median =3.95\space cm + \frac{0.5\cdot24-11}{4} \cdot 0.1=3.95 \space cm+0.025 \space cm=3.975\space cm
\end{aligned}
$$

<justify>
 수식을 이용한 도수분포표에서의 중위수는 3.975로 나왔다.
</justify>

-   **히스토그램**

``` r
library('ggplot2')
ggplot(ex3_1, aes(x=Length)) +  geom_histogram(binwidth = 0.1, fill='#8dd3c7',colour='#ffffb3')+
  scale_x_continuous(breaks = seq(0,4.5,0.1))
```

![](/study/img/ch3/unnamed-chunk-8-1.png)


<justify>
히스토그램을 보면 날개의 길이가 4인 경우의 빈도수가 4로 가장 많은것을 알 수 있다.
</justify>
<br/>
<justify>
나비 날개 길이의 frequency table 출력 결과를 살펴보면 표본평균 값이 3.96이고 중앙값이 3.975이므로 두 값이 서로 비슷한 것을 확인할 수 있다.<br/>따라서 거의 치우치지 않은 분포의 형태를 띄고 있는 것을 알 수 있고 히스토그램을 통해서도 확인할 수 있다.
</justify>


### EXAMPLE 3.3

![](/study/img/ch3/3-3.png)

``` r
#데이터셋
ex3_3
```

    ##    exam3_3.Group exam3_3.LifeSpan
    ## 1              A               16
    ## 2              A               32
    ## 3              A               37
    ## 4              A               39
    ## 5              A               40
    ## 6              A               41
    ## 7              A               42
    ## 8              A               50
    ## 9              A               82
    ## 10             B               34
    ## 11             B               36
    ## 12             B               38
    ## 13             B               45
    ## 14             B               50
    ## 15             B               54
    ## 16             B               56
    ## 17             B               59
    ## 18             B               69
    ## 19             B               91

``` r
ex3_3$exam3_3.LifeSpan
```

    ##  [1] 16 32 37 39 40 41 42 50 82 34 36 38 45 50 54 56 59 69 91

``` r
ex3_3_a <- subset(ex3_3,exam3_3.Group=="A")
ex3_3_b <- subset(ex3_3,exam3_3.Group=="B")
a_n <- length(ex3_3_a$exam3_3.Group) 
b_n <- length(ex3_3_b$exam3_3.Group)
a_med <- median(ex3_3_a$exam3_3.LifeSpan) 
b_med <- median(ex3_3_b$exam3_3.LifeSpan)
a_mn <- round(mean(ex3_3_a$exam3_3.LifeSpan),2) ;
b_mn <- mean(ex3_3_b$exam3_3.LifeSpan)

cat(" Number of Species A = ",a_n,",  Median of Species A = ",a_med, ",  Mean of Species A = ",a_mn,"\n",
    "Number of Species B = ",b_n,",  Median of Species B = ",b_med, ",  Mean of Species B = ",b_mn)
```

    ##  Number of Species A =  9 ,  Median of Species A =  40 ,  Mean of Species A =  42.11 
    ##  Number of Species B =  10 ,  Median of Species B =  52 ,  Mean of Species B =  53.2


|  |Species A|Species B |
|:---|:---|:---|
|$n$|9|10|
|$median$|40|52|
|$\overline X$|42.11|53.20|


<justify>
A종의 새 9마리와 B종의 새 10마리를 관측했을 때, A종의 경우 수명 중위수는 40개월, 평균 수명은 42.11개월이며 B종의 경우 수명 중위수는 52개월, 평균 수명은 53.20개월로 측정되었다.
</justify>

### EXAMPLE 3.4

![](/study/img/ch3/3-4.png)

``` r
#데이터셋
ex3_4
```

    ##   exam3_4.decade exam3_4.population exam3_4.ratio
    ## 1              0              10000            NA
    ## 2              1              10500          1.05
    ## 3              2              11550          1.10
    ## 4              3              13860          1.20
    ## 5              4              18156          1.31

<justify>
기하평균은 인구증가율 등을 구할 때 사용되는 평균이며 데이터가 같지 않다면 기하평균은 산술평균보다 항상 작다는 특징이 있다.
</justify>

$$
\overline X_G =
\begin{cases}
Method \ 1) ^n \sqrt{X_1 X_2 X_3 \cdots X_n} \\
Method \ 2) antilog(\frac{logX_1 + logX_2 + \cdots + logX_n}{n}) \\
\end{cases}
$$

-   Manually

``` r
x_bar <- mean(na.omit(ex3_4$exam3_4.ratio))
geo_mean_x_method1 <- exp(mean(log(na.omit(ex3_4$exam3_4.ratio)))) 
geo_mean_x_method2 <- prod(na.omit(ex3_4$exam3_4.ratio)) ^ (1/length(na.omit(ex3_4$exam3_4.ratio)))
cat('Geometric Mean Manually =', '('  ,'method1 =', geo_mean_x_method1, ',' ,'method2 =' ,geo_mean_x_method2,')')
```

    ## Geometric Mean Manually = ( method1 = 1.160803 , method2 = 1.160803 )

-   Package

``` r
library(psych)
geo_mean_x_package <- geometric.mean(ex3_4$exam3_4.ratio) ; cat('Geometric Mean with psych package =', geo_mean_x_package)
```

    ## Geometric Mean with psych package = 1.160803

<justify>
기하 평균은 데이터 곱의 n 제곱근(Method 1)으로 나타낼 수 있으며,<br/>데이터 로그 변환의 산술 평균을 다시 역로그변환(지수변환) (Method 2)으로 나타낼 수 있다.<br/>변화율의 산술 평균은 1.165이며, 이 때 기하 평균은 두 가지 방법 및 패키지를 이용하였을 때 1.1608로 동일하게 산출된다.
</justify>

``` r
first_p <- ex3_4$exam3_4.population[1] # 초기 population
final_p_a  <- round(first_p*mean(ex3_4$exam3_4.ratio[2:5])^4)
final_p_g <- round(first_p*round(geometric.mean(ex3_4$exam3_4.ratio[2:5]),4)^4)
cat(" 산술평균으로 구한 Final Population = ",final_p_a,"\n","기하평균으로 구한 Final Population = ",final_p_g) 
```

    ##  산술평균으로 구한 Final Population =  18421 
    ##  기하평균으로 구한 Final Population =  18156

<justify>
앞서 구한 산술평균과 기하평균을 이용해 마지막 인구집단 사이즈를 구해보았다.
</justify>

### EXAMPLE 3.5

![](/study/img/ch3/3-5.png)

``` r
#데이터셋
ex3_5
```

    ##    X
    ## 1 40
    ## 2 20

<justify>
조화평균은 평균의 변화율을 구할 떄 주로 사용되며 데이터가 양수이고 비척도인 경우에 이용한다
</justify>

$$
\overline X_H = \frac{n}{\sum \frac{1}{X_i}}
$$

- Manually

``` r
harmonic_mean_manual <- round(length(ex3_5$X) / sum(1/ex3_5$X),2) ; cat('Harmonic Mean Manually =', harmonic_mean_manual)
```

    ## Harmonic Mean Manually = 26.67

- Package

``` r
library(psych)
harmonic_mean_package <- round(harmonic.mean(ex3_5$X),2) ; cat('Harmonic Mean with psych package =', harmonic_mean_package)
```

    ## Harmonic Mean with psych package = 26.67

<justify>
수식을 이용한 방식과 패키지를 이용하여 조화 평균을 산출 했을 때 값이 26.67로 같은 값이 산출된다.
</justify>
<br/>

``` r
xm <- mean(ex3_5$X)
cat("산술평균=", xm, "km/h,   조화평균=",harmonic_mean_manual,"km/h")
```

    ## 산술평균= 30 km/h,   조화평균= 26.67 km/h
<justify>
이처럼 전체 거리를 절반은40km/h로 달리고 나머지는 20km/h로 달렸다면,<br/>평균속력은 40과 20의 조화평균인 26.67 km/h가 된다.
</justify>

### EXAMPLE 3.6

![](/study/img/ch3/3-6.png)

``` r
#데이터셋
ex3_6
```

    ##   exam3_6.X1 exam3_6.code1 exam3_6.X2 exam3_6.code2
    ## 1        842             2       8000          8000
    ## 2        844             4       9000          9000
    ## 3        846             6      95000         95000
    ## 4        846             6      11000         11000
    ## 5        847             7      12500         12500
    ## 6        848             8      13000         13000
    ## 7        849             9         NA            NA

<justify>
The mean of the coded values is equal to $\bar{X} - 840 g$.
</justify>

``` r
A <- -840 ; M <- 0.001

sum_sample1 <- sum(ex3_6$exam3_6.X1)
coded_sum_sample1 <- sum(ex3_6$exam3_6.code1)
mean_sample1 <- mean(ex3_6$exam3_6.X1)
coded_mean_sample1 <- mean(ex3_6$exam3_6.code1)

mean_sample1 <-  coded_mean_sample1-A
mean_sample1
```

    ## [1] 846

<justify>
The mean of the coded values is equal to $\bar{X} * M$.
</justify>

``` r
#데이터 오기 수정하기
ex3_6$exam3_6.X2[3] <- ex3_6$exam3_6.X2[3]/10
ex3_6$exam3_6.code2[3] <- ex3_6$exam3_6.code2[3]/10

#결측값제외하고 계산
sum_sample2 <- sum(na.omit(ex3_6$exam3_6.X2))
coded_sum_sample2 <- sum(na.omit(ex3_6$exam3_6.code2*M))
mean_sample2 <- mean(na.omit(ex3_6$exam3_6.X2))
coded_mean_sample2 <- mean(na.omit(ex3_6$exam3_6.code2*M))

mean_sample2 <-  coded_mean_sample2 / M
mean_sample2
```

    ## [1] 10500



|stat / Group| Sample 1 | Sample 2 |
|------------|----------|----------|
|Sum         |5922      |63000     |
|coded Sum   |42        |63        |
|Mean        |846       |10500     |
|coded Mean  |6         |10.5      |

<br/>

</div>
</details>


<br/>

# SAS 프로그램 결과

<details>
<summary>
sas 접기/펼치기 버튼
</summary>
<div markdown="1">
```python
import saspy #SAS출력 코드
```

winlocal 입력

## 1장

**1장 연습문제 불러오기**

```python
%%SAS

libname ex 'C:\Biostat';
run;

/*1장 연습문제 불러오기*/
%macro chap01_1(name=,no=);
%do i=1 %to &no.;
	PROC IMPORT DBMS=excel
		DATAFILE="C:\Biostat\data_chap01"
		OUT=ex.&name.&i. REPLACE;
		RANGE="exam1_&i.$";
	RUN;
%end;
%mend;

%macro chap01_2(name=,no=);
	PROC IMPORT DBMS=excel
		DATAFILE="C:\Biostat\data_chap01"
		OUT=ex.&name.&no. REPLACE;
		RANGE="exam1_&no.$";
	RUN;
%mend;

%chap01_1(name=ex1_,no=5);
%chap01_2(name=ex1_,no=4a);
%chap01_2(name=ex1_,no=4b);
```

###  EXAMPLE 1.1



```python
%%SAS

/*둥지 개수를 bar graph로 출력하기*/
title 'The Location of Sparrow Ners';

/*bar plot1*/
PROC SGPLOT DATA=ex.ex1_1;
    styleattrs datacolors=('#fb8072' "#8dd3c7" "#bebada" "#ffffb3" "#80b1d3") datacontrastcolors=('#fb8072' "#8dd3c7" "#bebada" "#ffffb3" "#80b1d3");
    vbarparm category=nestsite response=number / group=nestsite;
	yaxis label="Number of Nests" ;
	xaxis label="Nest Site";
RUN;

/*bar plot2 : 세로축이 45부터 시작되는 그래프*/
PROC SGPLOT DATA=ex.ex1_1;
    styleattrs datacolors=('#fb8072' "#8dd3c7" "#bebada" "#ffffb3" "#80b1d3") datacontrastcolors=('#fb8072' "#8dd3c7" "#bebada" "#ffffb3" "#80b1d3");
    vbarparm category=nestsite response=number / group=nestsite;
    yaxis grid values=(45 to 60 by 5) 
    label="Number of Nests" labelattrs=(size=7pt);
    xaxis label="Net Site";
RUN;
```


<html lang="ko" xml:lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8"/>
<meta content="SAS 9.4" name="generator"/>
<title>SAS 출력</title>
<style>
/*<![CDATA[*/
.body.c > table, .body.c > pre, .body.c div > table,
.body.c div > pre, .body.c > table, .body.c > pre,
.body.j > table, .body.j > pre, .body.j div > table,
.body.j div > pre, .body.j > table, .body.j > pre,
.body.c p.note, .body.c p.warning, .body.c p.error, .body.c p.fatal,
.body.j p.note, .body.j p.warning, .body.j p.error, .body.j p.fatal,
.body.c > table.layoutcontainer, .body.j > table.layoutcontainer { margin-left: auto; margin-right: auto }
.layoutregion.l table, .layoutregion.l pre, .layoutregion.l p.note,
.layoutregion.l p.warning, .layoutregion.l p.error, .layoutregion.l p.fatal { margin-left: 0 }
.layoutregion.c table, .layoutregion.c pre, .layoutregion.c p.note,
.layoutregion.c p.warning, .layoutregion.c p.error, .layoutregion.c p.fatal { margin-left: auto; margin-right: auto }
.layoutregion.r table, .layoutregion.r pre, .layoutregion.r p.note,
.layoutregion.r table, .layoutregion.r pre, .layoutregion.r p.note,
.layoutregion.r p.warning, .layoutregion.r p.error, .layoutregion.r p.fatal { margin-right: 0 }
article, aside, details, figcaption, figure, footer, header, hgroup, nav, section { display: block }
html{ font-size: 100% }
.body { margin: 1em; font-size: 13px; line-height: 1.231 }
sup { position: relative; vertical-align: baseline; bottom: 0.25em; font-size: 0.8em }
sub { position: relative; vertical-align: baseline; top: 0.25em; font-size: 0.8em }
ul, ol { margin: 1em 0; padding: 0 0 0 40px }
dd { margin: 0 0 0 40px }
nav ul, nav ol { list-style: none; list-style-image: none; margin: 0; padding: 0 }
img { border: 0; vertical-align: middle }
svg:not(:root) { overflow: hidden }
figure { margin: 0 }
table { border-collapse: collapse; border-spacing: 0 }
.layoutcontainer { border-collapse: separate; border-spacing: 0 }
p { margin-top: 0; text-align: center }
h1.heading1 { text-align: center }
h2.heading2 { text-align: center }
h3.heading3 { text-align: center }
h4.heading4 { text-align: center }
h5.heading5 { text-align: center }
h6.heading6 { text-align: center }
span { text-align: center }
table { margin-bottom: 1em }
td, th { text-align: center; padding: 3px 6px; vertical-align: top }
td[class$="fixed"], th[class$="fixed"] { white-space: pre }
section, article { padding-top: 1px; padding-bottom: 8px }
hr.pagebreak { height: 0px; border: 0; border-bottom: 1px solid #c0c0c0; margin: 1em 0 }
.stacked-value { text-align: center; display: block }
.stacked-cell > .stacked-value, td.data > td.data, th.data > td.data, th.data > th.data, td.data > th.data, th.header > th.header { border: 0 }
.stacked-cell > div.data { border-width: 0 }
.systitleandfootercontainer { white-space: nowrap; margin-bottom: 1em }
.systitleandfootercontainer > p { margin: 0 }
.systitleandfootercontainer > p > span { display: inline-block; width: 100%; white-space: normal }
.batch { display: table }
.toc { display: none }
.proc_note_group, .proc_title_group { margin-bottom: 1em }
p.proctitle { margin: 0 }
p.note, p.warning, p.error, p.fatal { display: table }
.notebanner, .warnbanner, .errorbanner, .fatalbanner,
.notecontent, .warncontent, .errorcontent, .fatalcontent { display: table-cell; padding: 0.5em }
.notebanner, .warnbanner, .errorbanner, .fatalbanner { padding-right: 0 }
.body > div > ol li { text-align: center }
.beforecaption > h4 { margin-top: 0; margin-bottom: 0 }
.c { text-align: center }
.r { text-align: center }
.l { text-align: center }
.j { text-align: justify }
.d { text-align: center }
.b { vertical-align: bottom }
.m { vertical-align: middle }
.t { vertical-align: top }
.accessiblecaption {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
a:hover { color: #800080 }
.aftercaption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    padding-top: 4pt;
}
.batch > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.batch > tbody, .batch > thead, .batch > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.batch { border: hidden; }
.batch {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    padding: 7px;
    }
.beforecaption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.body {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    margin-left: 8px;
    margin-right: 8px;
}
.bodydate {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    text-align: center;
    vertical-align: top;
    width: 100%;
}
.bycontentfolder {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.byline {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
</div>
</details>


<font color='#fb8072'>교재: Biostatistical Analysis (5th Edition) by Jerrold H. Zar (z-lib.org)</font><br/>

<font color='#fb8072'> **이 글은 22학년도 1학기 의학통계방법론 과제 자료들을 정리한 글입니다.** </font>