---
layout: post
title:  "[의학통계방법론] Ch17. Simple Linear Regression"
category:
    - Study
    - 의학통계방법론
tag: [R, SAS, blog, jekyll, Jupyter, Data, Python]
toc: true
---
* this unordered seed list will be replaced by the toc
{:toc}

- 뒤로가기를 누르시면 목차로 되돌아옵니다. 😉

# Simple Linear Regression

# R 프로그램 결과

<details>
<summary>
R 접기/펼치기 버튼
</summary>
<div markdown="1">

**패키지**
<details>
<summary>
설치된 패키지 접기/펼치기 버튼
</summary>

<div markdown="1">

``` r
getwd()
```

    ## [1] "C:/Biostat"

``` r
library("dplyr")
library("kableExtra")
library("ggplot2")
library("chemCal")
library("broom")
```

</div>
</details>

## 17장

### EXAMPLE 17.1

![](/study/img/의학통계방법론/ch17/17-1.png)

``` r
#데이터셋
age <- c(3.0,4.0,5.0,6.0,8.0,9.0,10.0,11.0,12.0,14.0,15.0,16.0,17.0)
wing_length<-c(1.4,1.5,2.2,2.4,3.1,3.2,3.2,3.9,4.1,4.7,4.5,5.2,5.0)
ex17_1 <- data.frame(age,wing_length)
ex17_1 %>%
  kbl(caption = "Dataset of Example 17.1") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset of Example 17.1
</caption>
<thead>
<tr>
<th style="text-align:right;">
age
</th>
<th style="text-align:right;">
wing_length
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.4
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1.5
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
2.2
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
2.4
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
3.1
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
3.2
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
3.2
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
3.9
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
4.1
</td>
</tr>
<tr>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
4.7
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
4.5
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
5.2
</td>
</tr>
<tr>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
5.0
</td>
</tr>
</tbody>
</table>

- 해당 데이터는 참새의 나이와 날개의 길이를 측정한 데이터이다. <br/>
- 이 데이터를 사용하여 연령과 날개 길이의 회귀직선을 그려보도록 한다.

``` r
library("ggplot2")
ggplot(ex17_1, aes(x=age, y=wing_length)) + 
  geom_point(color="#8dd3c7",size=4) + 
  stat_smooth(method = 'lm', color="#ffffb3")+
  ggtitle("Example 17.1 : Sparrow wing length as a function of age")+
  ylab("Wing Length Y.in cm")+
  xlab("Age. X. in days")+
  theme_bw()
```

![](/study/img/의학통계방법론/ch17/unnamed-chunk-3-1.png)


### EXAMPLE 17.2

![](/study/img/의학통계방법론/ch17/17-2.png)

- EXAMPLE 17.1 데이터로 Machine formula를 사용하여 회귀식을 구하도록 한다.

$$
\begin{aligned}
n&=13 \ \ \ \ \ \ \ \ \ \overline X=\frac{130}{10}=13 \ \ \ \ \ \overline Y=\frac{44.4}{10}=3.415\\ \\
\sum x^2 &= \sum X^2 - \frac{(\sum X)^2}{n} = 1562-\frac{130^2}{13}=262\\ \\
\sum xy&= \sum XY - \frac{\sum X \ * \sum Y }{n}=514.80-\frac{130*44}{13}=70.8\\ \\
b &= \frac{\sum xy}{\sum x^2}= \frac{70.8}{262}=0.270\ cm/day \\ \\
a &= \overline Y - b \overline X=3.415\ cm-(0.270\ cm/day)(10\ days)\\ \\
&= 3.415\ cm-2.7\ cm=0.715\ cm\\ \\
\therefore \hat Y &= 0.715+0.270X
\end{aligned}
$$

``` r
f_17_2 <- function(x){
  n <- nrow(x)
  sum_x <- sum(x[,1])
  mean_x <- mean(x[,1])
  sum_y <- sum(x[,2])
  mean_y <- mean(x[,2])
  sum_x2 <- sum(x[,1]^2)
  sum_xy <- sum(x[,1]*x[,2])
  b <- (sum_xy-((sum_x*sum_y)/n))/(sum_x2-(sum_x^2)/n)
  a <- mean_y - b*mean_x
  out <- data.frame(n,sum_x,mean_x,sum_y,mean_y,sum_x2,sum_xy,b,a)
  return(out)
}

f_17_2(ex17_1)%>%
  kbl(caption = "Result of simple linear regression equation",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Result of simple linear regression equation
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
sum_x
</th>
<th style="text-align:right;">
mean_x
</th>
<th style="text-align:right;">
sum_y
</th>
<th style="text-align:right;">
mean_y
</th>
<th style="text-align:right;">
sum_x2
</th>
<th style="text-align:right;">
sum_xy
</th>
<th style="text-align:right;">
b
</th>
<th style="text-align:right;">
a
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
44.4
</td>
<td style="text-align:right;">
3.415385
</td>
<td style="text-align:right;">
1562
</td>
<td style="text-align:right;">
514.8
</td>
<td style="text-align:right;">
0.270229
</td>
<td style="text-align:right;">
0.7130945
</td>
</tr>
</tbody>
</table>

- 회귀식을 추정한 결과 $$\hat Y = 0.715+0.270X$$ 로 도출되었다.<br/>
- Example 17.1에서 구한 회귀직선에 식을 넣으면 다음과 같다.

``` r
ggplot(ex17_1, aes(x=age, y=wing_length)) + 
  geom_point(color="#8dd3c7",size=4) + 
  stat_smooth(method = 'lm', color="#ffffb3")+
  ggtitle("Example 17.2 : Sparrow wing length as a function of age with simple linear regression equation")+
  ylab("Wing Length Y.in cm")+
  xlab("Age. X. in days")+
  theme_bw()+
  geom_text(x=15, y=4, label=expression(hat(Y) == paste(0.715," + ",0.270,X, " ",)), cex = 5) 
```

![](/study/img/의학통계방법론/ch17/unnamed-chunk-5-1.png)

### EXAMPLE 17.3

![](/study/img/의학통계방법론/ch17/17-3-1.png)

![](/study/img/의학통계방법론/ch17/17-3-2.png)

- 앞서 구한 회귀식의 ANOVA table을 작성하여 추정한 회귀식의 유의성을 판단하여 보겠다.

``` r
library("broom")
lm17_2 <- lm(wing_length~age,data=ex17_1)
aov17_2 <- anova(lm17_2)
aov17_2 %>% tidy() %>% 
  rename(" "="term","Sum Sq"="sumsq","Mean Sq"="meansq","F value"="statistic","Pr(>F)"="p.value") %>% 
  kable(caption = "ANOVA table",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
ANOVA table
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Mean Sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(\>F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
19.1322137
</td>
<td style="text-align:right;">
19.1322137
</td>
<td style="text-align:right;">
401.0875
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0.5247093
</td>
<td style="text-align:right;">
0.0477008
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>

``` r
summ <- summary(lm17_2)
data.frame(summ$r.squared,summ$adj.r.squared) %>% 
  rename("R square"="summ.r.squared","Adjusted R square"="summ.adj.r.squared") %>% 
  kable(caption = "R square",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
R square
</caption>
<thead>
<tr>
<th style="text-align:right;">
R square
</th>
<th style="text-align:right;">
Adjusted R square
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.9733066
</td>
<td style="text-align:right;">
0.97088
</td>
</tr>
</tbody>
</table>

$$
\begin{aligned}
H_0 &: Regression\ model\ is\ not\ significant \\
H_A &: Regression\ model\ is\ significant
\end{aligned}
$$

- 회귀직선의 유의성을 판단한 결과, F값은 401.09, p-value<0.001 이므로 $$H_0: \beta_1=0$$은 기각되었다. <br/>
따라서 유의수준 5%하에 회귀직선은 유의하다고 할 수 있다. <br/>
- 결정계수 값은 0.97로, 총변동중에서 회귀직선에 의해 설명되는 부분이 97%임을 확인하였다.

### EXAMPLE 17.4

![](/study/img/의학통계방법론/ch17/17-4.png)

- EXAMPLE 1,2에 사용된 데이터를 가지고 회귀계수의 유의성 검정을 하기 위해 t-test를 진행해 보도록 하겠다.

> 직접 함수를를 작성하여 구하여 보겠다.

``` r
f_17_4 <- function(x){
  alpha <- 0.05
  n <- nrow(x)
  estimate <- f_17_2(x)$b
  r2 <- summ$r.squared
  syx2 <- (sd(x[,2])*sqrt((1-r2)*(13-1)/(13-2)))^2
  sum_x2 <- sum(x[,1]^2)-(sum(x[,1])^2)/n
  se <- sqrt(syx2/sum_x2)
  t <- estimate/se
  crit <- qt(1-alpha/2,n-2)
  pvalue <- pt(t,n-2,lower.tail = F)
  if(pvalue < 0.05){
    Reject_H0 <- "yes"
  }else{
    Reject_H0 <- "No"
  }
  out <- data.frame(n,estimate,se,t,pvalue,Reject_H0)
  return(out)
}

f_17_4(ex17_1)%>%
  kbl(caption = "Result of t test",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Result of t test
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
se
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
pvalue
</th>
<th style="text-align:left;">
Reject_H0
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
0.270229
</td>
<td style="text-align:right;">
0.0134931
</td>
<td style="text-align:right;">
20.02717
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:left;">
yes
</td>
</tr>
</tbody>
</table>

> R에 내장된 함수로 구하여 보겠다.

``` r
summ$coefficients %>% 
  as.data.frame() %>% 
  kable(caption = "Coefficient",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Coefficient
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(\>\|t\|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.7130945
</td>
<td style="text-align:right;">
0.1479045
</td>
<td style="text-align:right;">
4.821319
</td>
<td style="text-align:right;">
0.0005347
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
0.2702290
</td>
<td style="text-align:right;">
0.0134931
</td>
<td style="text-align:right;">
20.027169
</td>
<td style="text-align:right;">
0.0000000
</td>
</tr>
</tbody>
</table>

- 본 검정의 가설은 다음과 같다.

$$
\begin{aligned}
H_0 &: \beta=0 \\
H_A &: \beta \ne 0
\end{aligned}
$$

- 회귀계수의 유의성 검정 결과 age에 대한 coefficient 값은 0.2702290, t 값은 20.02 이며 p-value<0.001 로써 유의수준 0.05보다 작아 귀무가설을 기각할 충분한 근거를 가진다. <br/>
-그러므로 유의수준 5%하에 회귀계수는 유의하다고 할 수 있다.  

### EXAMPLE 17.5

![](/study/img/의학통계방법론/ch17/17-5-1.png)

![](/study/img/의학통계방법론/ch17/17-5-2.png)

- 다음의 식을 통하여 표준오차를 구해해 신뢰구간을 예측해보도록 하겠겠다.

$$
\begin{aligned}
&n=13\\
&\hat Y_i=a+bX_+i=0.715+(0.270)(13)=422.5\ cm\\ \\
&a)\ s_{\hat Y_i} = \sqrt{s^2_{Y * X }(\frac{1}{n}+\frac{(X_i-\overline X)^2}{\sum x^2})}\\ \\
&b)\ (s_{\hat Y_i})_{m} =\sqrt{s^2_{Y * X }(\frac{1}{m}+\frac{1}{n}+\frac{(X_i-\overline X)^2}{\sum x^2})}\\ \\
&c)\ (s_{\hat Y_i})_{1} =\sqrt{s^2_{Y * X }(1+\frac{1}{n}+\frac{(X_i-\overline X)^2}{\sum x^2})}
\end{aligned}
$$
  
- 13 day old의 새들의 날개의 길이의 모평균은 얼마인지 표준오차를 구해 신뢰구간을 계산해보도록 하겠다.

``` r
f_17_5 <- function(x,param){
  alpha <- 0.05
  n <- nrow(x)
  b <- f_17_2(x)$b
  a <- f_17_2(x)$a
  yi <- a+b*param
  r2 <- summ$r.squared
  mean_x <- mean(x[,1])
  syx2 <- (sd(x[,2])*sqrt((1-r2)*(13-1)/(13-2)))^2
  sum_x <- sum(x[,1])
  sum_x2 <- sum(x[,1]^2)
  sumx2 <- sum_x2-(sum_x^2)/n
  syi <- sqrt(syx2*((1/param)+((param-mean_x)^2/(sum_x2-(sum_x^2)/n))))
  syi_10 <- sqrt(syx2*((1/10)+(1/param)+((param-mean_x)^2/(sum_x2-(sum_x^2)/n))))
  syi_1 <- sqrt(syx2*(1+(1/param)+((param-mean_x)^2/(sum_x2-(sum_x^2)/n))))
  crit <- qt(1-alpha/2,n-2)
  L1_1 <- yi-crit*syi
  L2_1 <- yi+crit*syi
  L1_2 <- yi-crit*syi_10
  L2_2 <- yi+crit*syi_10
  L1_3 <- yi-crit*syi_1
  L2_3 <- yi+crit*syi_1
  out <- data.frame(yi,syi,L1_1,L2_1,syi_10,L1_2,L2_2,syi_1,L1_3,L2_3)
  return(out)
}

f_17_5(ex17_1,13)%>%
  kbl(caption = "Result",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Result
</caption>
<thead>
<tr>
<th style="text-align:right;">
yi
</th>
<th style="text-align:right;">
syi
</th>
<th style="text-align:right;">
L1_1
</th>
<th style="text-align:right;">
L2_1
</th>
<th style="text-align:right;">
syi_10
</th>
<th style="text-align:right;">
L1_2
</th>
<th style="text-align:right;">
L2_2
</th>
<th style="text-align:right;">
syi_1
</th>
<th style="text-align:right;">
L1_3
</th>
<th style="text-align:right;">
L2_3
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
4.226072
</td>
<td style="text-align:right;">
0.0728552
</td>
<td style="text-align:right;">
4.065719
</td>
<td style="text-align:right;">
4.386425
</td>
<td style="text-align:right;">
0.100389
</td>
<td style="text-align:right;">
4.005117
</td>
<td style="text-align:right;">
4.447026
</td>
<td style="text-align:right;">
0.2302362
</td>
<td style="text-align:right;">
3.719325
</td>
<td style="text-align:right;">
4.732818
</td>
</tr>
</tbody>
</table>

- Equation a)를 사용하였을 때 13일 살의 새의 날개 길이의 모평균의 95% 신뢰구간은 [4.065, 4.386] 이며,<br/> 
b)를 사용했을 떄는 [4.005, 4.445] 그리고,<br/> 
c)를 사용했을 때는 [3.719, 4.731]이다.

### EXAMPLE 17.6

![](/study/img/의학통계방법론/ch17/17-6.png)

- Estimated Y Value에 대하여 검정을 진행하여 보겠겠다.

$$
\begin{aligned}
H_0 &: The \ mean \ population \ wing \ length \ of \ 13.0-day-birds \ is \ not \ greater \ than \ 4cm \\
H_A &: The \ mean \ population \ wing \ length \ of \ 13.0-day-birds \ is \ greater \ than \ 4cm  
\end{aligned}
$$

``` r
f_17_6 <- function(x,param,compare){
  alpha <- 0.05
  n <- nrow(x)
  b <- f_17_2(x)$b
  a <- f_17_2(x)$a
  yi <- a+b*param
  r2 <- summ$r.squared
  mean_x <- mean(x[,1])
  syx2 <- (sd(x[,2])*sqrt((1-r2)*(13-1)/(13-2)))^2
  sum_x <- sum(x[,1])
  sum_x2 <- sum(x[,1]^2)
  sumx2 <- sum_x2-(sum_x^2)/n
  syi <- sqrt(syx2*((1/param)+((param-mean_x)^2/(sum_x2-(sum_x^2)/n))))
  t <- (yi-compare)/syi
  crit <- qt(1-alpha/2,n-2)
  pvalue <- pt(t,n-2,lower.tail = F)
  if(pvalue < 0.05){
    Reject_H0 <- "yes"
  }else{
    Reject_H0 <- "No"
  }
  out <- data.frame(yi,t,crit,pvalue,Reject_H0)
  return(out)
}

f_17_6(ex17_1,param=13,compare=4)%>%
  kbl(caption = "Result",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Result
</caption>
<thead>
<tr>
<th style="text-align:right;">
yi
</th>
<th style="text-align:right;">
t
</th>
<th style="text-align:right;">
crit
</th>
<th style="text-align:right;">
pvalue
</th>
<th style="text-align:left;">
Reject_H0
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
4.226072
</td>
<td style="text-align:right;">
3.103028
</td>
<td style="text-align:right;">
2.200985
</td>
<td style="text-align:right;">
0.0050248
</td>
<td style="text-align:left;">
yes
</td>
</tr>
</tbody>
</table>

- 예측된 Y값 검정 결과 검정통계량 t값은 3.10이고 p-value=0.005 이므므로 유의수준 0.05보다 작아 귀무가설을 기각할 충분한 근거가 있다. <br/>
- 그러므로 유의수준5%하에 새들의 날개의 길이에 대한 모평균이 4cm 보다 크다는 충분한 근거가 있다고 할 수 있다.

### EXAMPLE 17.7

![](/study/img/의학통계방법론/ch17/17-7.png)

- 이번에는 y값이 주어졌을 때 x값을 구해보도록 하겠다.<br/>
- 즉, 날개의 길이가 주어졌을 때, 새들의 나이를 예측해보는 inverse에 관한 문제이다.<br/>
- 날개의 길이가 4.5cm 라고 했을 때 신뢰구간을 구하는 방식은 다음과 같다.

$$
\begin{aligned}
&\overline X + \frac{b(Y_i - \overline Y)}{K} \pm \frac{t}{K}\sqrt{(s^2_{Y*X})'[\frac{(Y_i-\overline Y)^2}{\sum x^2}+K(\frac{1}{m}+\frac{1}{n})]}\\ \\
&where\ \ t=t_{\alpha(2),(n+m-3)}, \ \ \ K=b^2-t^2(s_b^2)'\\ \\
&(s_b^2)'=\frac{(s_{Y*X}^2)'}{\sum x^2}, \ \ \ \ \  (s_{Y*X}^2)'=residual\ SS+\sum_{j=1}^m (Y_{ij}-\overline Y_i)^2/(n+m-3)
\end{aligned}
$$

> R의 chemCal 패키지의 inverse.predict() 함수를 사용하여 구해보겠다.

``` r
library("chemCal")
inverse_result <- inverse.predict(lm17_2,4.5)
inverse_result <- as.data.frame(inverse_result)
inverse_result[2,1:3] <- "."
inverse_result %>%
  kbl(caption = "Result of Inverse Prediction",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Result of Inverse Prediction
</caption>
<thead>
<tr>
<th style="text-align:left;">
Prediction
</th>
<th style="text-align:left;">
Standard.Error
</th>
<th style="text-align:left;">
Confidence
</th>
<th style="text-align:right;">
Confidence.Limits
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
14.0136897001304
</td>
<td style="text-align:left;">
0.862343975232319
</td>
<td style="text-align:left;">
1.89800629238076
</td>
<td style="text-align:right;">
12.11568
</td>
</tr>
<tr>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
.
</td>
<td style="text-align:left;">
.
</td>
<td style="text-align:right;">
15.91170
</td>
</tr>
</tbody>
</table>

- 위의 결과를 보아 날개의 길이가 4.5cm라고 주어졌을 때, <br/>
예상되는 새의 나이의 값은 14.013이고,<br/> 
이에 대한 95% 신뢰구간은 [12.115, 15.911] 이다.

### EXAMPLE 17.8a

![](/study/img/의학통계방법론/ch17/17-8a.png)

``` r
#데이터셋
age<-c(rep(30,3),rep(40,4),rep(50,3),rep(60,5),rep(70,5))
sbp<-c(108,110,106,125,120,118,119,132,137,134,148,151,146,147,144,162,156,164,158,159)
ex17_8 <- data.frame(age,sbp)
ex17_8 %>%
  kbl(caption = "Dataset of Example 17_8a",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset of Example 17_8a
</caption>
<thead>
<tr>
<th style="text-align:right;">
age
</th>
<th style="text-align:right;">
sbp
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
108
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
110
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
106
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
125
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
120
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
118
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
119
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
132
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
137
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
134
</td>
</tr>
<tr>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
148
</td>
</tr>
<tr>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
151
</td>
</tr>
<tr>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
146
</td>
</tr>
<tr>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
147
</td>
</tr>
<tr>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
144
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
162
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
156
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
164
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
158
</td>
</tr>
<tr>
<td style="text-align:right;">
70
</td>
<td style="text-align:right;">
159
</td>
</tr>
</tbody>
</table>

- 해당 데이터는 나이와 이에 따른 수축기혈압의 데이터이다.<br/>
- 각각의 x에 대해 multiple value Y를 가지는 회귀분석에 대한 문제이다.

> 모형의 유의성 검정

$$
\begin{aligned}
H_0 &: Regression\ model\ is\ not\ significant \\
H_A &: Regression\ model\ is\ significant 
\end{aligned}
$$

``` r
lm17_8 <- lm(sbp~age,data=ex17_8)
aov17_8 <- anova(lm17_8)
aov17_8%>% tidy() %>% 
  rename(" "="term","Sum Sq"="sumsq","Mean Sq"="meansq","F value"="statistic","Pr(>F)"="p.value") %>% 
  kable(caption = "ANOVA table",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
ANOVA table
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Mean Sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(\>F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
6750.2893
</td>
<td style="text-align:right;">
6750.289308
</td>
<td style="text-align:right;">
1021.819
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
118.9107
</td>
<td style="text-align:right;">
6.606149
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>

- 모형의 유의성 검정 결과 검정통계량 F값은 1021.819, p-value<0.001이므로 유의수준 0.05보다 작아 귀무가설을 기각할 충분한 근거를 가진다. <br/>
- 그러므로 유의수준 5%하에 회귀모형은 유의하다고 할 수 있다.

> 회귀계수의 유의성 검정

$$
\begin{aligned}
H_0 &: \beta=0 \\
H_A &: \beta \ne 0  
\end{aligned}
$$

``` r
summary(lm17_8)[4] %>% 
  as.data.frame %>% 
  rename("Estimate"="coefficients.Estimate","Standard Error"="coefficients.Std..Error","t value"="coefficients.t.value","Pr(>F)"="coefficients.Pr...t..") %>% 
  kable(caption = "Test of Coefficients",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Test of Coefficients
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Standard Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(\>F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
68.784906
</td>
<td style="text-align:right;">
2.2160746
</td>
<td style="text-align:right;">
31.03907
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
1.303145
</td>
<td style="text-align:right;">
0.0407667
</td>
<td style="text-align:right;">
31.96590
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>

- 회귀계수의 유의성 검정 결과 검정통계량 t값은 31.039, p-value<0.001이므로 유의수준 0.05보다 작아 귀무가설을 기각할 충분한 근거를 갖는다. <br/>
- 그러므로 유의수준 5%하에 회귀계수는 유의하다고 할 수 있다.<br/>
- 추정된 회귀식은 $$\hat Y_{ij}=68.78+1.303X_{ij}$$ 이다. <br/><br/>
- 회귀선을 그려보면 다음과 같다.  

``` r
ggplot(ex17_8, aes(x=age, y=sbp)) + 
  geom_point(color="#8dd3c7",size=4) + 
  stat_smooth(method = 'lm', color="#ffffb3")+
  ggtitle("Example 17.8 : A regression whewe there are multiple values of Y for each value of X")+
  ylab("Symbolic Blood Pressure Y.in mm Hg")+
  xlab("Age. X. in days")+
  theme_bw()+
  geom_text(x=60, y=160, label=expression(hat(Yij) == paste(68.78," + ",1.303,Xij, " ",)), cex = 7) 
```

![](/study/img/의학통계방법론/ch17/unnamed-chunk-16-1.png)

### EXAMPLE 17.8b

![](/study/img/의학통계방법론/ch17/17-8b-1.png)

![](/study/img/의학통계방법론/ch17/17-8b-2.png)

- EXAMPLE 17.8a에서 구한 회귀모형의 선형성 검정을 위해 적합결여 F-test 를 수행하도록 하겠다. <br/>
- 선형성 검정을 하기 위해서는 단순 선형모형을 고려한 축소모형과 설명변수 각각의 값들을 factor화 하여 적합한 모형인 전체모형을 구한 뒤 Reduced model과 Full model 사이의 분산분석을 통하여 선형성을 검정한다.

> Reduced model

``` r
rm <- lm(sbp~age,data=ex17_8)
summary(rm) %>% tidy %>% 
  rename("t value"="statistic","P value"="p.value") %>% 
  kable(caption = "Reduced model",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Reduced model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
P value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
68.784906
</td>
<td style="text-align:right;">
2.2160746
</td>
<td style="text-align:right;">
31.03907
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
1.303145
</td>
<td style="text-align:right;">
0.0407667
</td>
<td style="text-align:right;">
31.96590
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>

> Full model

``` r
fm <- lm(sbp~factor(age),data=ex17_8)
summary(fm) %>% tidy %>% 
  rename("t value"="statistic","P value"="p.value") %>% 
  kable(caption = "Reduced model",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Reduced model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std.error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
P value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
108.00000
</td>
<td style="text-align:right;">
1.614288
</td>
<td style="text-align:right;">
66.902558
</td>
<td style="text-align:right;">
0.00e+00
</td>
</tr>
<tr>
<td style="text-align:left;">
factor(age)40
</td>
<td style="text-align:right;">
12.50000
</td>
<td style="text-align:right;">
2.135502
</td>
<td style="text-align:right;">
5.853424
</td>
<td style="text-align:right;">
3.17e-05
</td>
</tr>
<tr>
<td style="text-align:left;">
factor(age)50
</td>
<td style="text-align:right;">
26.33333
</td>
<td style="text-align:right;">
2.282948
</td>
<td style="text-align:right;">
11.534793
</td>
<td style="text-align:right;">
0.00e+00
</td>
</tr>
<tr>
<td style="text-align:left;">
factor(age)60
</td>
<td style="text-align:right;">
39.20000
</td>
<td style="text-align:right;">
2.041931
</td>
<td style="text-align:right;">
19.197516
</td>
<td style="text-align:right;">
0.00e+00
</td>
</tr>
<tr>
<td style="text-align:left;">
factor(age)70
</td>
<td style="text-align:right;">
51.80000
</td>
<td style="text-align:right;">
2.041931
</td>
<td style="text-align:right;">
25.368146
</td>
<td style="text-align:right;">
0.00e+00
</td>
</tr>
</tbody>
</table>

> 선형성 검정 (Lack-of-fit test)

$$
\begin{aligned}
H_0 &: The \ population \ regression \ is \ linear. \\
H_A &: The \ population \ regression \ is \ not \ linear. 
\end{aligned}
$$

``` r
lof <- anova(rm,fm)
lof %>% tidy %>% 
  rename("Res df"="df.residual","RSS"="rss","Sum sq"="sumsq","F value"="statistic","P value"="p.value") %>% 
  kable(caption = "Reduced model",booktabs = TRUE, valign = 't') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Reduced model
</caption>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
Res df
</th>
<th style="text-align:right;">
RSS
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
Sum sq
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
P value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
sbp \~ age
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
118.9107
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
sbp \~ factor(age)
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
117.2667
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.644025
</td>
<td style="text-align:right;">
0.0700977
</td>
<td style="text-align:right;">
0.9750327
</td>
</tr>
</tbody>
</table>

- 적합결여 검정 결과 검정통계량 F값은 0.07, p-value=0.975 이므로 유의수준 0.05보다 커 귀무가설을 기각할 충분한 근거를 가지고있지 않다. <br/>
- 그러므로 유의수준 5%하에 모 회귀모델은 선형성을 따른다고 할 충분한 근거가 있다고 할 수 있다.

### EXAMPLE 17.9

![](/study/img/의학통계방법론/ch17/17-9.png)

``` r
#데이터셋
X<-c(rep(5,4),rep(10,4),rep(15,4),rep(20,4),rep(25,4))
Y<-c(10.72,11.22,11.75,12.31,14.13,14.79,15.49,16.22,18.61,19.50,20.40,21.37, 24.55,25.70,26.92,28.18,32.36,33.88,35.48,37.15)

ex17_9 <- data.frame(X,Y)
ex17_9%>%
  kbl(caption = "Dataset of Example 17_9",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset of Example 17_9
</caption>
<thead>
<tr>
<th style="text-align:right;">
X
</th>
<th style="text-align:right;">
Y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
10.72
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
11.22
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
11.75
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
12.31
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
14.13
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
14.79
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
15.49
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
16.22
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
18.61
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
19.50
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
20.40
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
21.37
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
24.55
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
25.70
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
26.92
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
28.18
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
32.36
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
33.88
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
35.48
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
37.15
</td>
</tr>
</tbody>
</table>

- 원 데이터와 로그변환한 데이터 간의 차이를 확인해보도록 하겠다.

> 로그변환

``` r
log_y <- log(Y,base=10)
ex17_9_trans <- data.frame(X,log_y)
ex17_9_trans%>%
  kbl(caption = "Logarithmic transformation Dataset of Example 17_9",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Logarithmic transformation Dataset of Example 17_9
</caption>
<thead>
<tr>
<th style="text-align:right;">
X
</th>
<th style="text-align:right;">
log_y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1.030195
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1.049993
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1.070038
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1.090258
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
1.150142
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
1.169968
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
1.190051
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
1.210051
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
1.269746
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
1.290035
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
1.309630
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
1.329805
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1.390051
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1.409933
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1.430075
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1.449941
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
1.510009
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
1.529943
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
1.549984
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
1.569959
</td>
</tr>
</tbody>
</table>

``` r
ex17_9_result1 <- lm(Y~X, data=ex17_9)
#ex17.9_result1$residuals
ex17_9_result2 <- lm(log_y~X, data=ex17_9_trans)
#ex17.9_result2$residuals
```

``` r
par(mfrow=c(1,2))
plot(X, Y, pch=16,las=1,xlab="X", ylab="Y",ylim=c(0,40),xlim=c(0,25), main="The original data", cex.main=1, col="#8f7450")
abline(coef(ex17_9_result1), lwd=2, col="orange")
plot(X,log_y,pch=16,las=1,xlab="X",ylab="Y",ylim=c(1.0,1.6),xlim=c(0,25), main="The data after transformation", cex.main=1, col="#8f7450")
abline(coef(ex17_9_result2), lwd=2, col="orange")
```

![](/study/img/의학통계방법론/ch17/unnamed-chunk-23-1.png)

``` r
par(mfrow=c(1,2))
plot(X, ex17_9_result1$residuals, xlab="X", ylab="residuals", main = "The original data", cex.main=1, pch=16, col="#8dd3c7")
plot(X, ex17_9_result2$residuals, xlab="X", ylab="residuals", main = "The data after transformation", cex.main=1, pch=16, col="#8dd3c7")
```

![](/study/img/의학통계방법론/ch17/unnamed-chunk-24-1.png)

``` r
par(mfrow=c(1,2))
qqnorm(ex17_9_result1$residuals, main = "The original data", cex.main=1, pch=16, col="#8dd3c7")
qqnorm(ex17_9_result2$residuals, main = "The data after transformation", cex.main=1, pch=16, col="#8dd3c7")
```

![](/study/img/의학통계방법론/ch17/unnamed-chunk-25-1.png)

- 데이터를 로그변환하였을 때 더 강한 선형성을 가짐을 알 수 있다. <br/>
- 그리고 로그변환하였을 때의 잔차의 절대값이 변환 전보다 크게 줄었음을 알 수 있다.

``` r
origin <- c(var(Y[ex17_9$X==5]),var(Y[ex17_9$X==10]),var(Y[ex17_9$X==15]),var(Y[ex17_9$X==20]),var(Y[ex17_9$X==25])) 
logtrans <- c(var(log_y[ex17_9_trans$X==5]),var(log_y[ex17_9_trans$X==10]),var(log_y[ex17_9_trans$X==15]),var(log_y[ex17_9_trans$X==20]),var(log_y[ex17_9_trans$X==25])) 
variance <- data.frame(origin,logtrans)
variance%>%
  kbl(caption = "Variance of each of original data set Logarithmic transformation",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Variance of each of original data set Logarithmic transformation
</caption>
<thead>
<tr>
<th style="text-align:right;">
origin
</th>
<th style="text-align:right;">
logtrans
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.4684667
</td>
<td style="text-align:right;">
0.0006682
</td>
</tr>
<tr>
<td style="text-align:right;">
0.8100917
</td>
<td style="text-align:right;">
0.0006654
</td>
</tr>
<tr>
<td style="text-align:right;">
1.4051333
</td>
<td style="text-align:right;">
0.0006652
</td>
</tr>
<tr>
<td style="text-align:right;">
2.4452250
</td>
<td style="text-align:right;">
0.0006654
</td>
</tr>
<tr>
<td style="text-align:right;">
4.2525583
</td>
<td style="text-align:right;">
0.0006659
</td>
</tr>
</tbody>
</table>

</div>
</details>

<br/>

# SAS 프로그램 결과

<details>
<summary>
SAS 접기/펼치기 버튼
</summary>
<div markdown="1">

## 17장

### EXAMPLE 17.1


~~~sas
DATA ex17_1;
INPUT age wing @@;
CARDS;
3 1.4 4 1.5 5 2.2 6 2.4 8 3.1 9 3.2 
10 3.2 11 3.9 12 4.1 14 4.7 15 4.5 16 5.2 17 5
;
RUN;

PROC PRINT DATA=ex17_1;
RUN;
~~~


<html lang="ko" xml:lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8"/>
<meta content="SAS 9.4" name="generator"/>
<title>SAS 출력</title>
<style>
/*<![CDATA[*/
.body.c > table, .body.c > pre, .body.c div > table,
.body.c div > pre, .body.c > table, .body.c > pre,
.body.j > table, .body.j > pre, .body.j div > table,
.body.j div > pre, .body.j > table, .body.j > pre,
.body.c p.note, .body.c p.warning, .body.c p.error, .body.c p.fatal,
.body.j p.note, .body.j p.warning, .body.j p.error, .body.j p.fatal,
.body.c > table.layoutcontainer, .body.j > table.layoutcontainer { margin-left: auto; margin-right: auto }
.layoutregion.l table, .layoutregion.l pre, .layoutregion.l p.note,
.layoutregion.l p.warning, .layoutregion.l p.error, .layoutregion.l p.fatal { margin-left: 0 }
.layoutregion.c table, .layoutregion.c pre, .layoutregion.c p.note,
.layoutregion.c p.warning, .layoutregion.c p.error, .layoutregion.c p.fatal { margin-left: auto; margin-right: auto }
.layoutregion.r table, .layoutregion.r pre, .layoutregion.r p.note,
.layoutregion.r table, .layoutregion.r pre, .layoutregion.r p.note,
.layoutregion.r p.warning, .layoutregion.r p.error, .layoutregion.r p.fatal { margin-right: 0 }
article, aside, details, figcaption, figure, footer, header, hgroup, nav, section { display: block }
html{ font-size: 100% }
.body { margin: 1em; font-size: 13px; line-height: 1.231 }
sup { position: relative; vertical-align: baseline; bottom: 0.25em; font-size: 0.8em }
sub { position: relative; vertical-align: baseline; top: 0.25em; font-size: 0.8em }
ul, ol { margin: 1em 0; padding: 0 0 0 40px }
dd { margin: 0 0 0 40px }
nav ul, nav ol { list-style: none; list-style-image: none; margin: 0; padding: 0 }
img { border: 0; vertical-align: middle }
svg:not(:root) { overflow: hidden }
figure { margin: 0 }
table { border-collapse: collapse; border-spacing: 0 }
.layoutcontainer { border-collapse: separate; border-spacing: 0 }
p { margin-top: 0; text-align: center }
h1.heading1 { text-align: center }
h2.heading2 { text-align: center }
h3.heading3 { text-align: center }
h4.heading4 { text-align: center }
h5.heading5 { text-align: center }
h6.heading6 { text-align: center }
span { text-align: center }
table { margin-bottom: 1em }
td, th { text-align: center; padding: 3px 6px; vertical-align: top }
td[class$="fixed"], th[class$="fixed"] { white-space: pre }
section, article { padding-top: 1px; padding-bottom: 8px }
hr.pagebreak { height: 0px; border: 0; border-bottom: 1px solid #c0c0c0; margin: 1em 0 }
.stacked-value { text-align: center; display: block }
.stacked-cell > .stacked-value, td.data > td.data, th.data > td.data, th.data > th.data, td.data > th.data, th.header > th.header { border: 0 }
.stacked-cell > div.data { border-width: 0 }
.systitleandfootercontainer { white-space: nowrap; margin-bottom: 1em }
.systitleandfootercontainer > p { margin: 0 }
.systitleandfootercontainer > p > span { display: inline-block; width: 100%; white-space: normal }
.batch { display: table }
.toc { display: none }
.proc_note_group, .proc_title_group { margin-bottom: 1em }
p.proctitle { margin: 0 }
p.note, p.warning, p.error, p.fatal { display: table }
.notebanner, .warnbanner, .errorbanner, .fatalbanner,
.notecontent, .warncontent, .errorcontent, .fatalcontent { display: table-cell; padding: 0.5em }
.notebanner, .warnbanner, .errorbanner, .fatalbanner { padding-right: 0 }
.body > div > ol li { text-align: center }
.beforecaption > h4 { margin-top: 0; margin-bottom: 0 }
.c { text-align: center }
.r { text-align: center }
.l { text-align: center }
.j { text-align: justify }
.d { text-align: center }
.b { vertical-align: bottom }
.m { vertical-align: middle }
.t { vertical-align: top }
.accessiblecaption {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
a:hover { color: #800080 }
.aftercaption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    padding-top: 4pt;
}
.batch > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.batch > tbody, .batch > thead, .batch > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.batch { border: hidden; }
.batch {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    padding: 7px;
    }
.beforecaption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.body {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    margin-left: 8px;
    margin-right: 8px;
}
.bodydate {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    text-align: center;
    vertical-align: top;
    width: 100%;
}
.bycontentfolder {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.byline {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.bylinecontainer > col, .bylinecontainer > colgroup > col, .bylinecontainer > colgroup, .bylinecontainer > tr, .bylinecontainer > * > tr, .bylinecontainer > thead, .bylinecontainer > tbody, .bylinecontainer > tfoot { border: none; }
.bylinecontainer {
    background-color: #fafbfe;
    border: none;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.caption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.cell, .container {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.contentfolder, .contentitem {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.contentproclabel, .contentprocname {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.contents {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: decimal;
    margin-left: 8px;
    margin-right: 8px;
}
.contentsdate {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.contenttitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: bold;
}
.continued {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    width: 100%;
}
.data, .dataemphasis {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.dataemphasisfixed {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.dataempty {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.datafixed {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.datastrong {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.datastrongfixed {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.date {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.document {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.errorbanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.errorcontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.errorcontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.extendedpage {
    background-color: #fafbfe;
    border-style: solid;
    border-width: 1pt;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
    text-align: center;
}
.fatalbanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.fatalcontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.fatalcontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.folderaction {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.footer {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.footeremphasis {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.footeremphasisfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.footerempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.footerfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.footerstrong {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.footerstrongfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.frame {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.graph > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.graph > tbody, .graph > thead, .graph > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.graph { border: hidden; }
.graph {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    }
.header {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headeremphasis {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.headeremphasisfixed {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.headerempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headerfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.headersandfooters {
    background-color: #edf2f9;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headerstrong {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headerstrongfixed {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.heading1, .heading2, .heading3, .heading4, .heading5, .heading6 { font-family: Gulim, Helvetica, sans-serif }
.index {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.indexaction, .indexitem {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.indexprocname {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.indextitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: bold;
}
.layoutcontainer, .layoutregion {
    border-width: 0;
    border-spacing: 30px;
}
.linecontent {
    background-color: #fafbfe;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.list {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: disc;
}
.list10 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.list2 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: circle;
}
.list3, .list4, .list5, .list6, .list7, .list8, .list9 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.listitem {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: disc;
}
.listitem10 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.listitem2 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: circle;
}
.listitem3, .listitem4, .listitem5, .listitem6, .listitem7, .listitem8, .listitem9 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.note {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.notebanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.notecontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.notecontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.output > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.output > tbody, .output > thead, .output > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.output { border: hidden; }
.output {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    }
.pageno {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    text-align: center;
    vertical-align: top;
}
.pages {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: decimal;
    margin-left: 8px;
    margin-right: 8px;
}
.pagesdate {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.pagesitem {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.pagesproclabel, .pagesprocname {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.pagestitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: bold;
}
.paragraph {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.parskip > col, .parskip > colgroup > col, .parskip > colgroup, .parskip > tr, .parskip > * > tr, .parskip > thead, .parskip > tbody, .parskip > tfoot { border: none; }
.parskip {
    border: none;
    border-spacing: 0;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    }
.prepage {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    text-align: center;
}
.proctitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.proctitlefixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooter {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooteremphasis {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowfooteremphasisfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowfooterempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooterfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.rowfooterstrong {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooterstrongfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheader {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheaderemphasis {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowheaderemphasisfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowheaderempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheaderfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.rowheaderstrong {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheaderstrongfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.systemfooter, .systemfooter10, .systemfooter2, .systemfooter3, .systemfooter4, .systemfooter5, .systemfooter6, .systemfooter7, .systemfooter8, .systemfooter9 {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.systemtitle, .systemtitle10, .systemtitle2, .systemtitle3, .systemtitle4, .systemtitle5, .systemtitle6, .systemtitle7, .systemtitle8, .systemtitle9 {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size: small;
    font-style: normal;
    font-weight: bold;
}
.systitleandfootercontainer > col, .systitleandfootercontainer > colgroup > col, .systitleandfootercontainer > colgroup, .systitleandfootercontainer > tr, .systitleandfootercontainer > * > tr, .systitleandfootercontainer > thead, .systitleandfootercontainer > tbody, .systitleandfootercontainer > tfoot { border: none; }
.systitleandfootercontainer {
    background-color: #fafbfe;
    border: none;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.table > col, .table > colgroup > col {
    border-left: 1px solid #c1c1c1;
    border-right: 0 solid #c1c1c1;
}
.table > tr, .table > * > tr {
    border-top: 1px solid #c1c1c1;
    border-bottom: 0 solid #c1c1c1;
}
.table { border: hidden; }
.table {
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 1px 0 0 1px;
    border-collapse: collapse;
    border-spacing: 0;
    }
.titleandnotecontainer > col, .titleandnotecontainer > colgroup > col, .titleandnotecontainer > colgroup, .titleandnotecontainer > tr, .titleandnotecontainer > * > tr, .titleandnotecontainer > thead, .titleandnotecontainer > tbody, .titleandnotecontainer > tfoot { border: none; }
.titleandnotecontainer {
    background-color: #fafbfe;
    border: none;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.titlesandfooters {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.usertext {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.warnbanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.warncontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.warncontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
/*]]>*/
</style>
</head>
<body class="l body">
<div style="padding-bottom: 8px; padding-top: 1px">
<div id="IDX" class="systitleandfootercontainer" style="border-spacing: 1px">
<p><span class="c systemtitle">SAS 시스템</span> </p>
</div>
<div style="padding-bottom: 8px; padding-top: 1px">
<table class="table" style="border-spacing: 0" aria-label="데이터셋 WORK.EX17_1">
<caption aria-label="데이터셋 WORK.EX17_1"></caption>
<colgroup><col/></colgroup><colgroup><col/><col/></colgroup>
<thead>
<tr>
<th class="r header" scope="col">OBS</th>
<th class="r header" scope="col">age</th>
<th class="r header" scope="col">wing</th>
</tr>
</thead>
<tbody>
<tr>
<th class="r rowheader" scope="row">1</th>
<td class="r data">3</td>
<td class="r data">1.4</td>
</tr>
<tr>
<th class="r rowheader" scope="row">2</th>
<td class="r data">4</td>
<td class="r data">1.5</td>
</tr>
<tr>
<th class="r rowheader" scope="row">3</th>
<td class="r data">5</td>
<td class="r data">2.2</td>
</tr>
<tr>
<th class="r rowheader" scope="row">4</th>
<td class="r data">6</td>
<td class="r data">2.4</td>
</tr>
<tr>
<th class="r rowheader" scope="row">5</th>
<td class="r data">8</td>
<td class="r data">3.1</td>
</tr>
<tr>
<th class="r rowheader" scope="row">6</th>
<td class="r data">9</td>
<td class="r data">3.2</td>
</tr>
<tr>
<th class="r rowheader" scope="row">7</th>
<td class="r data">10</td>
<td class="r data">3.2</td>
</tr>
<tr>
<th class="r rowheader" scope="row">8</th>
<td class="r data">11</td>
<td class="r data">3.9</td>
</tr>
<tr>
<th class="r rowheader" scope="row">9</th>
<td class="r data">12</td>
<td class="r data">4.1</td>
</tr>
<tr>
<th class="r rowheader" scope="row">10</th>
<td class="r data">14</td>
<td class="r data">4.7</td>
</tr>
<tr>
<th class="r rowheader" scope="row">11</th>
<td class="r data">15</td>
<td class="r data">4.5</td>
</tr>
<tr>
<th class="r rowheader" scope="row">12</th>
<td class="r data">16</td>
<td class="r data">5.2</td>
</tr>
<tr>
<th class="r rowheader" scope="row">13</th>
<td class="r data">17</td>
<td class="r data">5.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</body>
</html>





~~~sas
ods graphics off;ods exclude all;ods noresults;
PROC REG DATA=ex17_1;
   MODEL wing=age;
   ODS OUTPUT ParameterEstimates=PE;
RUN;

DATA _null_;
   SET PE;
   IF _n_ = 1 THEN CALL symput('Int', put(estimate, BEST6.));   
   ELSE CALL symput('Slope', put(estimate, BEST6.)); 
RUN;
ods graphics on;ods exclude none;ods results;

title 'wing*age';
PROC SGPLOT DATA=ex17_1 NOAUTOLEGEND;
   REG y=wing x=age;
   INSET "Intercept = &Int" "Slope = &Slope" /
   BORDER title="Parameter Estimates" position=topleft;
RUN;
~~~





<html lang="ko" xml:lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8"/>
<meta content="SAS 9.4" name="generator"/>
<title>SAS 출력</title>
<style>
/*<![CDATA[*/
.body.c > table, .body.c > pre, .body.c div > table,
.body.c div > pre, .body.c > table, .body.c > pre,
.body.j > table, .body.j > pre, .body.j div > table,
.body.j div > pre, .body.j > table, .body.j > pre,
.body.c p.note, .body.c p.warning, .body.c p.error, .body.c p.fatal,
.body.j p.note, .body.j p.warning, .body.j p.error, .body.j p.fatal,
.body.c > table.layoutcontainer, .body.j > table.layoutcontainer { margin-left: auto; margin-right: auto }
.layoutregion.l table, .layoutregion.l pre, .layoutregion.l p.note,
.layoutregion.l p.warning, .layoutregion.l p.error, .layoutregion.l p.fatal { margin-left: 0 }
.layoutregion.c table, .layoutregion.c pre, .layoutregion.c p.note,
.layoutregion.c p.warning, .layoutregion.c p.error, .layoutregion.c p.fatal { margin-left: auto; margin-right: auto }
.layoutregion.r table, .layoutregion.r pre, .layoutregion.r p.note,
.layoutregion.r table, .layoutregion.r pre, .layoutregion.r p.note,
.layoutregion.r p.warning, .layoutregion.r p.error, .layoutregion.r p.fatal { margin-right: 0 }
article, aside, details, figcaption, figure, footer, header, hgroup, nav, section { display: block }
html{ font-size: 100% }
.body { margin: 1em; font-size: 13px; line-height: 1.231 }
sup { position: relative; vertical-align: baseline; bottom: 0.25em; font-size: 0.8em }
sub { position: relative; vertical-align: baseline; top: 0.25em; font-size: 0.8em }
ul, ol { margin: 1em 0; padding: 0 0 0 40px }
dd { margin: 0 0 0 40px }
nav ul, nav ol { list-style: none; list-style-image: none; margin: 0; padding: 0 }
img { border: 0; vertical-align: middle }
svg:not(:root) { overflow: hidden }
figure { margin: 0 }
table { border-collapse: collapse; border-spacing: 0 }
.layoutcontainer { border-collapse: separate; border-spacing: 0 }
p { margin-top: 0; text-align: center }
h1.heading1 { text-align: center }
h2.heading2 { text-align: center }
h3.heading3 { text-align: center }
h4.heading4 { text-align: center }
h5.heading5 { text-align: center }
h6.heading6 { text-align: center }
span { text-align: center }
table { margin-bottom: 1em }
td, th { text-align: center; padding: 3px 6px; vertical-align: top }
td[class$="fixed"], th[class$="fixed"] { white-space: pre }
section, article { padding-top: 1px; padding-bottom: 8px }
hr.pagebreak { height: 0px; border: 0; border-bottom: 1px solid #c0c0c0; margin: 1em 0 }
.stacked-value { text-align: center; display: block }
.stacked-cell > .stacked-value, td.data > td.data, th.data > td.data, th.data > th.data, td.data > th.data, th.header > th.header { border: 0 }
.stacked-cell > div.data { border-width: 0 }
.systitleandfootercontainer { white-space: nowrap; margin-bottom: 1em }
.systitleandfootercontainer > p { margin: 0 }
.systitleandfootercontainer > p > span { display: inline-block; width: 100%; white-space: normal }
.batch { display: table }
.toc { display: none }
.proc_note_group, .proc_title_group { margin-bottom: 1em }
p.proctitle { margin: 0 }
p.note, p.warning, p.error, p.fatal { display: table }
.notebanner, .warnbanner, .errorbanner, .fatalbanner,
.notecontent, .warncontent, .errorcontent, .fatalcontent { display: table-cell; padding: 0.5em }
.notebanner, .warnbanner, .errorbanner, .fatalbanner { padding-right: 0 }
.body > div > ol li { text-align: center }
.beforecaption > h4 { margin-top: 0; margin-bottom: 0 }
.c { text-align: center }
.r { text-align: center }
.l { text-align: center }
.j { text-align: justify }
.d { text-align: center }
.b { vertical-align: bottom }
.m { vertical-align: middle }
.t { vertical-align: top }
.accessiblecaption {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
a:hover { color: #800080 }
.aftercaption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    padding-top: 4pt;
}
.batch > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.batch > tbody, .batch > thead, .batch > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.batch { border: hidden; }
.batch {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    padding: 7px;
    }
.beforecaption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.body {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    margin-left: 8px;
    margin-right: 8px;
}
.bodydate {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    text-align: center;
    vertical-align: top;
    width: 100%;
}
.bycontentfolder {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.byline {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.bylinecontainer > col, .bylinecontainer > colgroup > col, .bylinecontainer > colgroup, .bylinecontainer > tr, .bylinecontainer > * > tr, .bylinecontainer > thead, .bylinecontainer > tbody, .bylinecontainer > tfoot { border: none; }
.bylinecontainer {
    background-color: #fafbfe;
    border: none;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.caption {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.cell, .container {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.contentfolder, .contentitem {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.contentproclabel, .contentprocname {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.contents {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: decimal;
    margin-left: 8px;
    margin-right: 8px;
}
.contentsdate {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.contenttitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: bold;
}
.continued {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    width: 100%;
}
.data, .dataemphasis {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.dataemphasisfixed {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.dataempty {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.datafixed {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.datastrong {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.datastrongfixed {
    background-color: #ffffff;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.date {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.document {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.errorbanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.errorcontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.errorcontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.extendedpage {
    background-color: #fafbfe;
    border-style: solid;
    border-width: 1pt;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
    text-align: center;
}
.fatalbanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.fatalcontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.fatalcontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.folderaction {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.footer {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.footeremphasis {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.footeremphasisfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.footerempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.footerfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.footerstrong {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.footerstrongfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.frame {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.graph > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.graph > tbody, .graph > thead, .graph > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.graph { border: hidden; }
.graph {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    }
.header {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headeremphasis {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.headeremphasisfixed {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.headerempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headerfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.headersandfooters {
    background-color: #edf2f9;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headerstrong {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.headerstrongfixed {
    background-color: #d8dbd3;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #000000;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.heading1, .heading2, .heading3, .heading4, .heading5, .heading6 { font-family: Gulim, Helvetica, sans-serif }
.index {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.indexaction, .indexitem {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.indexprocname {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.indextitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: bold;
}
.layoutcontainer, .layoutregion {
    border-width: 0;
    border-spacing: 30px;
}
.linecontent {
    background-color: #fafbfe;
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.list {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: disc;
}
.list10 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.list2 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: circle;
}
.list3, .list4, .list5, .list6, .list7, .list8, .list9 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.listitem {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: disc;
}
.listitem10 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.listitem2 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: circle;
}
.listitem3, .listitem4, .listitem5, .listitem6, .listitem7, .listitem8, .listitem9 {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: square;
}
.note {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.notebanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.notecontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.notecontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.output > colgroup {
    border-left: 1px solid #c1c1c1;
    border-right: 1px solid #c1c1c1;
}
.output > tbody, .output > thead, .output > tfoot {
    border-top: 1px solid #c1c1c1;
    border-bottom: 1px solid #c1c1c1;
}
.output { border: hidden; }
.output {
    background-color: #fafbfe;
    border: 1px solid #c1c1c1;
    border-collapse: separate;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    }
.pageno {
    background-color: #fafbfe;
    border-spacing: 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    text-align: center;
    vertical-align: top;
}
.pages {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: decimal;
    margin-left: 8px;
    margin-right: 8px;
}
.pagesdate {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.pagesitem {
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    list-style-type: none;
    margin-left: 6pt;
}
.pagesproclabel, .pagesprocname {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.pagestitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: bold;
}
.paragraph {
    background-color: #fafbfe;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.parskip > col, .parskip > colgroup > col, .parskip > colgroup, .parskip > tr, .parskip > * > tr, .parskip > thead, .parskip > tbody, .parskip > tfoot { border: none; }
.parskip {
    border: none;
    border-spacing: 0;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
    }
.prepage {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    text-align: center;
}
.proctitle {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.proctitlefixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooter {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooteremphasis {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowfooteremphasisfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowfooterempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooterfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.rowfooterstrong {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowfooterstrongfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheader {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheaderemphasis {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowheaderemphasisfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: italic;
    font-weight: normal;
}
.rowheaderempty {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheaderfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.rowheaderstrong {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.rowheaderstrongfixed {
    background-color: #edf2f9;
    border-color: #b0b7bb;
    border-style: solid;
    border-width: 0 1px 1px 0;
    color: #112277;
    font-family: BatangChe, Courier, monospace, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.systemfooter, .systemfooter10, .systemfooter2, .systemfooter3, .systemfooter4, .systemfooter5, .systemfooter6, .systemfooter7, .systemfooter8, .systemfooter9 {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.systemtitle, .systemtitle10, .systemtitle2, .systemtitle3, .systemtitle4, .systemtitle5, .systemtitle6, .systemtitle7, .systemtitle8, .systemtitle9 {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size: small;
    font-style: normal;
    font-weight: bold;
}
.systitleandfootercontainer > col, .systitleandfootercontainer > colgroup > col, .systitleandfootercontainer > colgroup, .systitleandfootercontainer > tr, .systitleandfootercontainer > * > tr, .systitleandfootercontainer > thead, .systitleandfootercontainer > tbody, .systitleandfootercontainer > tfoot { border: none; }
.systitleandfootercontainer {
    background-color: #fafbfe;
    border: none;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.table > col, .table > colgroup > col {
    border-left: 1px solid #c1c1c1;
    border-right: 0 solid #c1c1c1;
}
.table > tr, .table > * > tr {
    border-top: 1px solid #c1c1c1;
    border-bottom: 0 solid #c1c1c1;
}
.table { border: hidden; }
.table {
    border-color: #c1c1c1;
    border-style: solid;
    border-width: 1px 0 0 1px;
    border-collapse: collapse;
    border-spacing: 0;
    }
.titleandnotecontainer > col, .titleandnotecontainer > colgroup > col, .titleandnotecontainer > colgroup, .titleandnotecontainer > tr, .titleandnotecontainer > * > tr, .titleandnotecontainer > thead, .titleandnotecontainer > tbody, .titleandnotecontainer > tfoot { border: none; }
.titleandnotecontainer {
    background-color: #fafbfe;
    border: none;
    border-spacing: 1px;
    color: #000000;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
    width: 100%;
}
.titlesandfooters {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.usertext {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.warnbanner {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: bold;
}
.warncontent {
    background-color: #fafbfe;
    color: #112277;
    font-family: Gulim, Helvetica, Helv, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
.warncontentfixed {
    background-color: #fafbfe;
    color: #112277;
    font-family: BatangChe, Courier, sans-serif;
    font-size:  normal;
    font-style: normal;
    font-weight: normal;
}
/*]]>*/
</style>
</head>
<body class="l body">
<div style="padding-bottom: 8px; padding-top: 1px">
</div>
<div style="padding-bottom: 8px; padding-top: 1px">
<div id="IDX" style="padding-bottom: 8px; padding-top: 1px">
<div class="c">
<script type="text/ecmascript">
var SVG_IDX_SVGRoot = null;
var SVG_IDX_TrueCoords = null;
var SVG_IDX_singleTip = null;
var SVG_IDX_singleBox = null;
var SVG_IDX_singleText = null;
var SVG_IDX_tiptspan = null;
var SVG_IDX_attrScale = 1;
var SVG_IDX_rightEdge = null;
var SVG_IDX_SVGHeight = null;
var SVG_IDX_SVGWidth = null;
function SVG_IDX_Init(anchor) {
   SVG_IDX_SVGRoot = document.getElementById(anchor);
   SVG_IDX_TrueCoords = SVG_IDX_SVGRoot.createSVGPoint();
   SVG_IDX_singleTip = document.getElementById(anchor + '_singleTip1');
   SVG_IDX_singleBox = document.getElementById(anchor + '_singleBox1');
   SVG_IDX_singleText = document.getElementById(anchor + '_singleText1');
   SVG_IDX_tiptspan = document.getElementById(anchor + '_tiptspan1');
   SVG_IDX_tiptspan.firstChild.nodeValue = null;
   SVG_IDX_SVGRoot.addEventListener('mousemove', SVG_IDX_ShowTooltip, false);
   SVG_IDX_SVGRoot.addEventListener('mouseout', SVG_IDX_HideTooltip, false);
   SVG_IDX_SVGHeight = SVG_IDX_SVGRoot.getAttributeNS(null, "height");
   SVG_IDX_SVGWidth = SVG_IDX_SVGRoot.getAttributeNS(null, "width");
   if (!isNaN(parseFloat(SVG_IDX_SVGHeight)) && !isNaN(parseFloat(SVG_IDX_SVGWidth)))
      SVG_IDX_GetHW();
}
function SVG_IDX_GetHW()
{
    if (SVG_IDX_SVGWidth != null && SVG_IDX_SVGWidth != "") {
       if (SVG_IDX_SVGWidth.match(/%/)) {
          var factor = parseFloat(SVG_IDX_SVGWidth.replace(/%/,""))/100;
          SVG_IDX_SVGWidth = window.innerWidth * factor;
       }
       else if (SVG_IDX_SVGWidth.match(/in/))
          SVG_IDX_SVGWidth = parseFloat(SVG_IDX_SVGWidth.replace(/in/,""))*96;
       else if (SVG_IDX_SVGWidth.match(/cm/))
          SVG_IDX_SVGWidth = parseFloat(SVG_IDX_SVGWidth.replace(/in/,""))*96/2.54;
       else
           SVG_IDX_SVGWidth = parseFloat(SVG_IDX_SVGWidth);
    }
    if (SVG_IDX_SVGHeight != null && SVG_IDX_SVGHeight != "") {
       if (SVG_IDX_SVGHeight.match(/%/)) {
          var factor = parseFloat(SVG_IDX_SVGHeight.replace(/%/,""))/100;
          SVG_IDX_SVGHeight = window.innerHeight * factor;
       }
       else if (SVG_IDX_SVGHeight.match(/in/))
          SVG_IDX_SVGHeight = parseFloat(SVG_IDX_SVGHeight.replace(/in/,""))*96;
       else if (SVG_IDX_SVGHeight.match(/cm/))
          SVG_IDX_SVGHeight = parseFloat(SVG_IDX_SVGHeight.replace(/in/,""))*96/2.54;
       else
           SVG_IDX_SVGHeight = parseFloat(SVG_IDX_SVGHeight);
    }
}
function SVG_IDX_GetScaleFactors(evt)
{
   var zoomFactor = 1;
   windowWidth  = (top.innerWidth==undefined)  ? window.innerWidth  : top.innerWidth;
   windowHeight = (top.innerHeight==undefined) ? window.innerHeight : top.innerHeight;
   SVG_IDX_rightEdge = (SVG_IDX_SVGWidth) ? SVG_IDX_SVGWidth - window.pageXOffset : windowWidth;
   if (parseFloat(SVG_IDX_SVGWidth) > 0 || parseFloat(SVG_IDX_SVGHeight) > 0)
      var tipScale = 1.875;
   else {
      var tipXScale  = (screen.width/windowWidth) / SVG_IDX_SVGRoot.currentScale;
      var tipYScale  = (screen.height/windowHeight) / SVG_IDX_SVGRoot.currentScale;
      var tipScale   = (tipXScale + tipYScale)/2.0;
   }
   SVG_IDX_attrScale = tipScale;
   if (navigator.appName == 'Adobe SVG Viewer') {
      if (screen.deviceXDPI != null && screen.logicalXDPI != null)
         zoomFactor = screen.deviceXDPI/screen.logicalXDPI;
      SVG_IDX_attrScale = zoomFactor*tipScale;
   }
   else if (navigator.userAgent != null && navigator.userAgent != '') {
      var ua = navigator.userAgent.toLowerCase();
      if (ua.indexOf("msie") != -1 || ua.indexOf("trident") != -1) {
         zoomFactor = screen.deviceXDPI/screen.logicalXDPI;
         SVG_IDX_attrScale = tipScale/zoomFactor;
         SVG_IDX_rightEdge /= zoomFactor;
      }
      else if (ua.indexOf("ipad") != -1) {
         zoomFactor = SVG_IDX_SVGRoot.clientWidth / window.innerWidth;
         SVG_IDX_attrScale = 1.5 / zoomFactor;
         SVG_IDX_rightEdge /= zoomFactor;
      }
      else if (ua.indexOf("opera") != -1)
         SVG_IDX_attrScale = tipScale;
      else if (ua.indexOf("firefox") != -1)
         SVG_IDX_attrScale = tipScale;
      else {
         if (SVG_IDX_SVGWidth > 0 || SVG_IDX_SVGHeight > 0)
            zoomFactor = 1;
         else
            zoomFactor = parseInt(document.defaultView.getComputedStyle(SVG_IDX_SVGRoot, null).width,10)/
                                  SVG_IDX_SVGRoot.clientWidth;
         SVG_IDX_attrScale = tipScale/zoomFactor;
         SVG_IDX_rightEdge *= zoomFactor;
      }
   }
}
function SVG_IDX_GetTrueCoords(evt)
{
   var trans = SVG_IDX_SVGRoot.currentTranslate;
   var scale = SVG_IDX_SVGRoot.currentScale;
   SVG_IDX_GetScaleFactors();
   var p1    = SVG_IDX_SVGRoot.createSVGPoint();
   var p2;
      var m = SVG_IDX_SVGRoot.getScreenCTM();
      if (navigator.userAgent.toLowerCase().indexOf("ipad") != -1) {
         p1.x = evt.clientX + window.pageXOffset;
         p1.y = evt.clientY + window.pageYOffset;
      }
      else {
      p1.x = evt.clientX;
      p1.y = evt.clientY;
      }
      p2 = p1.matrixTransform(m.inverse());
   SVG_IDX_TrueCoords.x = Math.round(p2.x*100) / 100;
   SVG_IDX_TrueCoords.y = Math.round(p2.y*100) / 100;
}
function SVG_IDX_HideTooltip( evt )
{
   SVG_IDX_tiptspan.firstChild.nodeValue = null;
   SVG_IDX_singleTip.setAttributeNS(null, 'visibility', 'hidden');
}
function SVG_IDX_ShowTooltip( evt )
{
   SVG_IDX_GetTrueCoords( evt );
   var targetElement = evt.target;
   var tspanCount = targetElement.getElementsByTagName('desc').length;
   if (tspanCount == 1) {
      var targetTspan = targetElement.getElementsByTagName('desc').item(0);
      if ( targetTspan) {
         if (targetTspan.firstChild != null)
            SVG_IDX_tiptspan.firstChild.nodeValue = targetTspan.firstChild.nodeValue; }
   }
   if ( '' != SVG_IDX_tiptspan.firstChild.nodeValue )
   {
      var outline = SVG_IDX_singleText.getBBox();
      SVG_IDX_singleBox.setAttributeNS(null, 'transform', 'scale(' + SVG_IDX_attrScale + ',' + SVG_IDX_attrScale + ')' );
      SVG_IDX_singleText.setAttributeNS(null, 'transform', 'scale(' + SVG_IDX_attrScale + ',' + SVG_IDX_attrScale + ')' );
      SVG_IDX_singleTip.setAttributeNS(null, 'visibility', 'visible');
      if (evt.clientX + ((outline.width + 8)/0.8) * SVG_IDX_attrScale > SVG_IDX_rightEdge) {
         var xPos = SVG_IDX_TrueCoords.x - parseInt((outline.width + 8)*SVG_IDX_attrScale);
         if (xPos < 0)
            xPos = 0;
      }
      else
         var xPos = SVG_IDX_TrueCoords.x;
      if (SVG_IDX_TrueCoords.y < 16) {
         var yPos = SVG_IDX_TrueCoords.y + ((outline.height + 16)/0.8)*SVG_IDX_attrScale;
         if (yPos > windowHeight)
            yPos = SVG_IDX_TrueCoords.y - parseInt((outline.height + 8)*SVG_IDX_attrScale);
      }
      else
         var yPos = SVG_IDX_TrueCoords.y - parseInt((outline.height + 8)*SVG_IDX_attrScale);
      if (Number(outline.width == 0))
         SVG_IDX_singleBox.setAttributeNS(null, 'width', outline.width);
      else
         SVG_IDX_singleBox.setAttributeNS(null, 'width', outline.width + 8);
      SVG_IDX_singleBox.setAttributeNS(null, 'height', outline.height + 8);
      SVG_IDX_singleTip.setAttributeNS(null, 'transform', 'translate(' + xPos + ',' + yPos + ')');
   }
}
</script>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" baseProfile="full" version="1.1" id="SVG_IDX" onload='SVG_IDX_Init("SVG_IDX")' viewBox="-1 -1 641 481" height="480" width="640">
<title>svgtitle</title>
<desc id="desc_SVG_IDX">SGPlot 프로시저</desc>
<defs>
<clipPath id="SVG_IDX_clipPage1">
<rect x="-1" y="-1" width="641" height="481"></rect>
</clipPath>
</defs>
<g id="SVG_IDX_Page1" clip-path="url(#SVG_IDX_clipPage1)">
<g transform=" scale(1, 1)">
<rect x="0" y="0" width="639" height="479" style="fill: #FFFFFF; "></rect>
<rect x="0" y="0" width="639" height="479" style="fill: #FFFFFF; "></rect>
<rect x="0" y="0" width="639" height="479" style="stroke: #D1D1D1; stroke-width: 1; fill: none; "></rect>
<g transform="matrix(1, 0, 0, 1, 11, 11)">
<defs>
<clipPath id="SVG_IDX_ClipPath0">
<rect x="-1" y="-1" width="619" height="459" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath0)">
<g transform="matrix(1, 0, 0, 1, 0, 23)">
<defs>
<clipPath id="SVG_IDX_ClipPath1">
<rect x="-1" y="-1" width="619" height="436" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath1)">
<rect x="45.92568" y="-0.0501" width="567.08239" height="385.15904" style="fill: #FFFFFF; "></rect>
<defs>
<clipPath id="SVG_IDX_ClipPath2">
<rect x="45" y="-1" width="569" height="387" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath2)">
<circle cx="72.28303" cy="377.12636" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="109.02358" cy="367.67678" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="145.76413" cy="301.52972" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="182.50468" cy="282.63056" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="255.98578" cy="216.48351" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="292.72633" cy="207.03393" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="329.46688" cy="207.03393" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="366.20743" cy="140.88687" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="402.94798" cy="121.98771" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="476.42907" cy="65.29024" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="513.16962" cy="84.1894" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="549.91017" cy="18.04234" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<circle cx="586.65072" cy="36.9415" r="3" style="stroke: #003399; stroke-width: 1; fill: none; stroke-linecap: square; "></circle>
<path d="M72.28303 365.42952L586.65072 7.93246" style="stroke: #667FA2; stroke-width: 2; fill: none; "></path>
</g>
<defs>
<clipPath id="SVG_IDX_ClipPath3">
<rect x="-1" y="-1" width="619" height="436" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath3)">
<path d="M45.92568 385.10893L613.00807 385.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<path d="M613.00807 385.10893L613.00807 -0.0501" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<path d="M45.92568 -0.0501L613.00807 -0.0501" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<path d="M45.92568 385.10893L45.92568 -0.0501" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<path d="M45.92568 385.10893L613.00807 385.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<path d="M53.91276 385.10893L53.91276 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 44.91276, 405.85893)">
<text textLength="18" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000032;&#x00002E;&#x000035;</text>
</g>
<path d="M145.76413 385.10893L145.76413 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 136.76413, 405.85893)">
<text textLength="18" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000035;&#x00002E;&#x000030;</text>
</g>
<path d="M237.6155 385.10893L237.6155 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 228.6155, 405.85893)">
<text textLength="18" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000037;&#x00002E;&#x000035;</text>
</g>
<path d="M329.46688 385.10893L329.46688 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 316.96688, 405.85893)">
<text textLength="25" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000031;&#x000030;&#x00002E;&#x000030;</text>
</g>
<path d="M421.31825 385.10893L421.31825 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 408.81825, 405.85893)">
<text textLength="25" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000031;&#x000032;&#x00002E;&#x000035;</text>
</g>
<path d="M513.16962 385.10893L513.16962 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 500.66962, 405.85893)">
<text textLength="25" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000031;&#x000035;&#x00002E;&#x000030;</text>
</g>
<path d="M605.021 385.10893L605.021 391.10893" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 592.521, 405.85893)">
<text textLength="25" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000031;&#x000037;&#x00002E;&#x000035;</text>
</g>
<g transform="matrix(1, 0, 0, 1, 320.96284, 429.35893)">
<text textLength="22" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 13px; white-space: pre; ">&#x000061;&#x000067;&#x000065;</text>
</g>
<path d="M45.92568 385.10893L45.92568 -0.0501" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<path d="M45.92568 320.42888L39.9223 320.42888" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 29.17018, 323.92888)">
<text textLength="7" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000032;</text>
</g>
<path d="M45.92568 225.93309L39.9223 225.93309" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 29.17018, 229.43309)">
<text textLength="7" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000033;</text>
</g>
<path d="M45.92568 131.43729L39.9223 131.43729" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 29.17018, 134.93729)">
<text textLength="7" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000034;</text>
</g>
<path d="M45.92568 36.9415L39.9223 36.9415" style="stroke: #989EA1; stroke-width: 1; fill: none; "></path>
<g transform="matrix(1, 0, 0, 1, 29.17018, 40.4415)">
<text textLength="7" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000035;</text>
</g>
<g transform="matrix(0, -1, 1, 0, 12.16171, 207.02941)">
<text textLength="29" lengthAdjust="spacingAndGlyphs" x="0" y="0.5" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 13px; white-space: pre; ">&#x000077;&#x000069;&#x00006E;&#x000067;</text>
</g>
</g>
</g>
</g>
<g transform="matrix(1, 0, 0, 1, 51, 28)">
<defs>
<clipPath id="SVG_IDX_ClipPath4">
<rect x="-1" y="-1" width="138" height="52" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath4)">
<rect x="0" y="0" width="136" height="50" style="stroke: #D1D1D1; stroke-width: 1; fill: none; "></rect>
<g transform="matrix(1, 0, 0, 1, 1, 18)">
<defs>
<clipPath id="SVG_IDX_ClipPath5">
<rect x="-1" y="-1" width="136" height="33" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath5)">
<g transform="matrix(1, 0, 0, 1, 0, 16)">
<defs>
<clipPath id="SVG_IDX_ClipPath6">
<rect x="-1" y="-1" width="136" height="17" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath6)">
<defs>
<clipPath id="SVG_IDX_ClipPath7">
<rect x="-1" y="-1" width="87" height="17" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath7)">
<text textLength="87" lengthAdjust="spacingAndGlyphs" x="3" y="10.30078" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000053;&#x00006C;&#x00006F;&#x000070;&#x000065;&#x000020;&#x00003D;&#x000020;&#x000030;&#x00002E;&#x000032;&#x000037;&#x000030;&#x000032;</text>
</g>
</g>
</g>
<defs>
<clipPath id="SVG_IDX_ClipPath8">
<rect x="-1" y="-1" width="136" height="17" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath8)">
<defs>
<clipPath id="SVG_IDX_ClipPath9">
<rect x="-1" y="-1" width="103" height="17" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath9)">
<text textLength="105" lengthAdjust="spacingAndGlyphs" x="3" y="10.30078" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 12px; white-space: pre; ">&#x000049;&#x00006E;&#x000074;&#x000065;&#x000072;&#x000063;&#x000065;&#x000070;&#x000074;&#x000020;&#x00003D;&#x000020;&#x000030;&#x00002E;&#x000037;&#x000031;&#x000033;&#x000031;</text>
</g>
</g>
</g>
</g>
<g transform="matrix(1, 0, 0, 1, 1, 1)">
<defs>
<clipPath id="SVG_IDX_ClipPath10">
<rect x="-1" y="-1" width="136" height="18" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath10)">
<defs>
<clipPath id="SVG_IDX_ClipPath11">
<rect x="-1" y="-1" width="136" height="18" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath11)">
<text textLength="121" lengthAdjust="spacingAndGlyphs" x="7" y="11.15918" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font3', 'Gulim', sans-serif; font-size: 13px; white-space: pre; ">&#x000050;&#x000061;&#x000072;&#x000061;&#x00006D;&#x000065;&#x000074;&#x000065;&#x000072;&#x000020;&#x000045;&#x000073;&#x000074;&#x000069;&#x00006D;&#x000061;&#x000074;&#x000065;&#x000073;</text>
</g>
</g>
</g>
</g>
</g>
<defs>
<clipPath id="SVG_IDX_ClipPath12">
<rect x="-1" y="-1" width="619" height="24" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath12)">
<g transform="matrix(1, 0, 0, 1, 294, 0)">
<defs>
<clipPath id="SVG_IDX_ClipPath13">
<rect x="-1" y="-1" width="74" height="19" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath13)">
<text textLength="67" lengthAdjust="spacingAndGlyphs" x="3" y="12.87597" style="fill: #000000; font-family: 'SVG_IDX_Gulim Font6', 'Gulim', sans-serif; font-size: 15px; white-space: pre; ">&#x000077;&#x000069;&#x00006E;&#x000067;&#x00002A;&#x000061;&#x000067;&#x000065;</text>
</g>
</g>
</g>
<g transform="matrix(1, 0, 0, 1, 0, 23)">
</g>
<defs>
<clipPath id="SVG_IDX_ClipPath14">
<rect x="45" y="-1" width="569" height="387" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath14)">
</g>
<defs>
<clipPath id="SVG_IDX_ClipPath15">
<rect x="-1" y="-1" width="619" height="459" ></rect>
</clipPath>
</defs>
<g clip-path="url(#SVG_IDX_ClipPath15)">
</g>
</g>
</g>
</g>
<rect x="0" y="0" width="640" height="480" fill="#FFFFFF" fill-opacity="0" aria-hidden="true">
<desc>SGPlot 프로시저
</div>
</details>

<br/>

<br/>

<font color='#fb8072'>교재: Biostatistical Analysis (5th Edition) by Jerrold H. Zar</font><br/>

<font color='#fb8072'> **이 글은 22학년도 1학기 의학통계방법론 과제 자료들을 정리한 글 입니다.** </font>