---
layout: post
title:  "[의학통계방법론] Ch19. Simple Linear Correlation"
category:
    - Study
    - 의학통계방법론
tag: [R, SAS, blog, jekyll, Jupyter, Data, Python]
toc: true
---
* this unordered seed list will be replaced by the toc
{:toc}

- 뒤로가기를 누르시면 목차로 되돌아옵니다. 😉

# Simple Linear Correlation

> [예제 데이터 링크 바로가기](https://github.com/James1verse27/James1verse27.github.io/tree/main/study/data/의학통계방법론/ch19)

# R 프로그램 결과

<details>
<summary>
R 접기/펼치기 버튼
</summary>
<div markdown="1">

**패키지**
<details>
<summary>
설치된 패키지 접기/펼치기 버튼
</summary>

<div markdown="1">

``` r
getwd()
```

    ## [1] "C:/Biostat"

``` r
library("foreign")
library("dplyr")
library("kableExtra")
library("GGally")
library("DescTools")
library("confintr")
library("diffcor")
library("remotes")
library("cower")
library("gtools")
library("psych")
library("ltm")
library("irr")
```

</div>
</details>

## 19장

**19장 연습문제 불러오기**

``` r
ex19_1a <- read.spss('Exam 19.1A.sav', to.data.frame=T)
ex19_12<- read.spss('Exam 19.12.sav', to.data.frame=T)
ex19_13<- read.spss('Exam 19.13.sav', to.data.frame=T)
ex19_14<- read.spss('Exam 19.14.sav', to.data.frame=T)
ex19_15<- read.spss('Exam 19.15.sav', to.data.frame=T)
ex19_16<- read.spss('Exam 19.16.sav', to.data.frame=T)
ex19_17<- read.spss('Exam 19.17.sav', to.data.frame=T)
ex19_18<- read.spss('Exam 19.18.sav', to.data.frame=T)
```

### EXAMPLE 19.1a

![](/study/img/의학통계방법론/ch19/19-1a.png)

``` r
#데이터셋
ex19_1a %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
WingLeingth
</th>
<th style="text-align:right;">
TailLength
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
10.4
</td>
<td style="text-align:right;">
7.4
</td>
</tr>
<tr>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
7.6
</td>
</tr>
<tr>
<td style="text-align:right;">
11.1
</td>
<td style="text-align:right;">
7.9
</td>
</tr>
<tr>
<td style="text-align:right;">
10.2
</td>
<td style="text-align:right;">
7.2
</td>
</tr>
<tr>
<td style="text-align:right;">
10.3
</td>
<td style="text-align:right;">
7.4
</td>
</tr>
<tr>
<td style="text-align:right;">
10.2
</td>
<td style="text-align:right;">
7.1
</td>
</tr>
<tr>
<td style="text-align:right;">
10.7
</td>
<td style="text-align:right;">
7.4
</td>
</tr>
<tr>
<td style="text-align:right;">
10.5
</td>
<td style="text-align:right;">
7.2
</td>
</tr>
<tr>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
7.8
</td>
</tr>
<tr>
<td style="text-align:right;">
11.2
</td>
<td style="text-align:right;">
7.7
</td>
</tr>
<tr>
<td style="text-align:right;">
10.6
</td>
<td style="text-align:right;">
7.8
</td>
</tr>
<tr>
<td style="text-align:right;">
11.4
</td>
<td style="text-align:right;">
8.3
</td>
</tr>
</tbody>
</table>

- 해당 데이터는 새의 날개의 길이와 꼬리의 길이를 측정한 대한 데이터이다.<br/>
- 새의 날개의 길이와 꼬리의 길이에 대하여 상관계수와 결정계수를 구하여 보겠다.

``` r
wing<-ex19_1a$WingLeingth
tail<-ex19_1a$TailLength

n=nrow(ex19_1a) ; 
sum_X=sum(wing) ; #x
sum_X2=sum(wing^2) ; #xx
sum_x2=sum((wing-mean(wing))^2) ; #x2

sum_Y=sum(tail) ; #y
sum_Y2=sum(tail^2)
sum_y2=sum((tail-mean(tail))^2) ; #y2
sum_XY=sum(wing*tail) ; #xxyy
sum_xy=sum((wing-mean(wing))*(tail-mean(tail))) ; #xy
r=sum_xy/sqrt(sum_x2*sum_y2) ; #r
r2=r^2

cbind(n, sum_X, sum_X2, sum_x2, sum_Y, sum_Y2, sum_y2, sum_XY, sum_xy, r, r2) %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
sum_X
</th>
<th style="text-align:right;">
sum_X2
</th>
<th style="text-align:right;">
sum_x2
</th>
<th style="text-align:right;">
sum_Y
</th>
<th style="text-align:right;">
sum_Y2
</th>
<th style="text-align:right;">
sum_y2
</th>
<th style="text-align:right;">
sum_XY
</th>
<th style="text-align:right;">
sum_xy
</th>
<th style="text-align:right;">
r
</th>
<th style="text-align:right;">
r2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
128.2
</td>
<td style="text-align:right;">
1371.32
</td>
<td style="text-align:right;">
1.716667
</td>
<td style="text-align:right;">
90.8
</td>
<td style="text-align:right;">
688.4
</td>
<td style="text-align:right;">
1.346667
</td>
<td style="text-align:right;">
971.37
</td>
<td style="text-align:right;">
1.323333
</td>
<td style="text-align:right;">
0.8703546
</td>
<td style="text-align:right;">
0.7575171
</td>
</tr>
</tbody>
</table>

- Pearson의 상관계수는 정규성 가정에서 출발하지 않았으며, 정규분포를 따르지 않더라도 1차 선형적인 연관성이 강하다면 구할 수 있다.<br/>
- 그래프를 그려서 선형성을 확인하여 보자.

``` r
plot(ex19_1a$WingLeingth,ex19_1a$TailLength,xlab = "Wing Length",ylab="Tail Length",main="Correlation",pch=19,col="#8dd3c7")
abline(lm(ex19_1a$TailLength ~ ex19_1a$WingLeingth), col = "#ffffb3", lwd = 4)
text(paste("Correlation:", round(r, 4)), x = 10.4, y = 8)
```

![](/study/img/의학통계방법론/unnamed-chunk-5-1.png)

``` r
library("GGally")
ggpairs(ex19_1a, colums=1:2)
```

![](/study/img/의학통계방법론/unnamed-chunk-6-1.png)

### EXAMPLE 19.1b

![](/study/img/의학통계방법론/ch19/19-1b.png)

- 상관계수에 대한 검정의 가설은 다음과 같다.

$$
\begin{aligned}
H_0 &: \rho=0 \\
H_A &: \rho \neq 0
\end{aligned}
$$

- R에 내장된 함수 cor.test()를 사용하여 양측검정을 시행하여 보겠다.
``` r
cor.test(ex19_1a$WingLeingth, ex19_1a$TailLength, alternative='two.sided')
```

    ## 
    ##  Pearson's product-moment correlation
    ## 
    ## data:  ex19_1a$WingLeingth and ex19_1a$TailLength
    ## t = 5.5893, df = 10, p-value = 0.0002311
    ## alternative hypothesis: true correlation is not equal to 0
    ## 95 percent confidence interval:
    ##  0.5923111 0.9631599
    ## sample estimates:
    ##       cor 
    ## 0.8703546

- 먼저 기본 옵션으로 제공되는 t-test에 대한 결과를 보면, t-값=5.5893이고, p-value=0.0002311로 유의수준 5%하에 대립가설을 채택한다.<br/>
- 따라서 상관계수는 0이 아니다라고 말할 수 있다.<br/><br/>
- p-value=0.002311이 나왔는데 문제에서는 p-value=0.00012로 다른 것을 볼 수 있다.<br/>
- 예제에서는 표본상관계수가 이미 양수로 나왔기 때문에 우측만 보고 의사결정을 한 경우이다.<br/>
- 그렇다면 단측검정을 시행하여서 p-value가 같은지 확인하여 보겠다.

``` r
cor.test(ex19_1a$WingLeingth, ex19_1a$TailLength, alternative='greater')
```

    ## 
    ##  Pearson's product-moment correlation
    ## 
    ## data:  ex19_1a$WingLeingth and ex19_1a$TailLength
    ## t = 5.5893, df = 10, p-value = 0.0001156
    ## alternative hypothesis: true correlation is greater than 0
    ## 95 percent confidence interval:
    ##  0.6562825 1.0000000
    ## sample estimates:
    ##       cor 
    ## 0.8703546

- p-value를 확인하여 보면 예제에서 나온 값이 같은 것을 볼 수 있다.<br/>
- R에서 나오는 기본 함수로는 t-test로 진행하지만 F통계량으로도 가설검정을 진행할 수 있다.

``` r
f<-(1+abs(r))/(1-abs(r))
f
```

    ## [1] 14.42669

- F 값은 14.4로써 3.72보다 크므로 귀무가설을 기각할 수 있다.

``` r
pf(f,10,10,lower.tail = F)
```

    ## [1] 0.000115553

- 단측가설의 대한 p-value=0.00012로써 유의수준 5%하에 귀무가설을 기각할 충분한 근거가 있으며,<br/>
- 예제에는 p-value는 양측에 대한 p-value가 구하여져 있기 때문에 좌측값 기준으로 계산된 p-value를 위에서 구한 p-value에 더해주면 양측에 대한 p-value가 구하여질 것이다.

### EXAMPLE 19.2

![](/study/img/의학통계방법론/ch19/19-2.png)

- 이 예제에서는 상관계수가 0이 아닌 상수 0.750이 아닌지에 대한 검정을 하고자 한다.

$$
\begin{aligned}
H_0 &: \rho=0.750 \\
H_A &: \rho \neq 0.750
\end{aligned}
$$

- 상관계수가 0이외에 다른 특정 값인지에 대해서도 검정을 진행하는 경우 tan변환을 통해 통계량을 구하고 검정을 진행한다.

$$
\begin{aligned}
z&=tanh^{-1}(r)=0.5\ ln(\frac{1+r}{1-r})\\
E(z)&=\zeta+\frac{\rho}{2(n-1)}\ \ \ Var(z)=\frac{1}{n-3}\ \ \ where,\ \zeta=tanh^{-1}(\rho)
\end{aligned}
$$

``` r
library("DescTools")
z<-FisherZ(r)
zeta<-FisherZ(0.75)
cat("z=",round(z,3),"zeta=",round(zeta,3))
```

    ## z= 1.335 zeta= 0.973

- Fisherz 함수를 이용하여 상관계수와 검정할 0.75를 변환시켰으며, 이 두 값으로 통계량 Z값을 구하여 보자.

``` r
Z<-(z-zeta)/sqrt(1/(n-3)); Z
```

    ## [1] 1.084755

``` r
pnorm(Z,lower.tail = F)*2
```

    ## [1] 0.2780303

- Z=1.08이고 이를 이용해 p-value를 구하면 0.28이다. <br/>
- 따라서 유의수준 0.05 하에서 귀무가설을 기각할 수 없고 모상관계수가 0.75가 아니라고 할만한 충분한 근거가 없다.
### EXAMPLE 19.3

![](/study/img/의학통계방법론/ch19/19-3.png)

- 상관계수에 대해서도 신뢰한계를 구할 수 있다. 

> 직접만든 함수로 구하여 보자.

``` r
f<-3.72
L1=((1+f)*r+(1-f))/((1+f)+(1-f)*r)
L2= ((1+f)*r-(1-f))/((1+f)-(1-f)*r)
cat("Confidence Limits for a Correlation Coefficient:",round(c(L1,L2),3))
```

    ## Confidence Limits for a Correlation Coefficient: 0.59 0.963

> cor.test()를 사용하여 구하여 보자.

``` r
CI<-cor.test(ex19_1a$WingLeingth, ex19_1a$TailLength, alternative="two.sided", method="pearson")
CI$conf.int
```

    ## [1] 0.5923111 0.9631599
    ## attr(,"conf.level")
    ## [1] 0.95

> ci_cor()를 사용하여 구하여 보자.

``` r
library("confintr")
ci_cor(ex19_1a$WingLeingth, ex19_1a$TailLength, method = "pearson",type="normal")
```

    ## 
    ##  Two-sided 95% normal confidence interval for the true Pearson
    ##  correlation coefficient
    ## 
    ## Sample estimate: 0.8703546 
    ## Confidence interval:
    ##      2.5%     97.5% 
    ## 0.5923111 0.9631599

### EXAMPLE 19.4

![](/study/img/의학통계방법론/ch19/19-4.png)

- 이 예제는 상관계수가 0인지를 검정할 때 그 가설을 기각하기 위한 power를 구하는 예제이다. 

$$
\begin{aligned}
L_1=\frac{(1+F_\alpha)r+(1-F_\alpha)}{(1+F_\alpha)+(1-F_\alpha)r}=\frac{4.11-2.72}{4.72-2.37}=0.592\\
L_2=\frac{(1+F_\alpha)r-(1-F_\alpha)}{(1+F_\alpha)-(1-F_\alpha)r}=\frac{4.11+2.72}{4.72+2.37}=0.963
\end{aligned}
$$

- pwr.r.test 패키지 함수를 이용하여 상관계수와 sample size, 유의수준, 양측검정인지 단측검정인지에 대해 입력하면 power를 계산할 수 있다.

``` r
library("pwr")
pw<-pwr.r.test(r, n=length(ex19_1a[,1]), sig.level = 0.05, alternative="two.sided")
cat("The power of the test is 1-β=",round(pw$power,2))
```

    ## The power of the test is 1-β= 0.98

### EXAMPLE 19.5a

![](/study/img/의학통계방법론/ch19/19-5a.png)

- 상관계수가 0인지를 검정할 때 그 가설을 기각하기 위한 sample size를 구하면 식은 다음과 같다. 

$$
n=(\frac{Z_{\beta(1)}+Z_\alpha}{\zeta_0})^2+3
$$

- pwr.r.test 패키지 함수를 이용하여 상관계수와 power, 유의수준, 양측검정인지 단측검정인지에 대해 입력하면 귀무가설을 기각할 수 있는 최소한의 sample size를 계산할 수 있다.

``` r
ex19_5a<-pwr.r.test(r=0.5, power=0.99, sig.level = 0.05, alternative = "two.sided")
cat("n=",round(ex19_5a$n,1))
```

    ## n= 63.1

- 계산 결과 n=63.1이므로 귀무가설을 기각하기 위한 최소한의 sample size는 64이다.

### EXAMPLE 19.5b

![](/study/img/의학통계방법론/ch19/19-5b-1.png)

![](/study/img/의학통계방법론/ch19/19-5b-2.png)

- pwr.r.test를 이용하는 방법 외에도 신뢰구간을 이용하여 귀무가설을 기각하기 위해 필요한 최소한의 sample size를 구할 수 있다.<br/>
- 예제 19.1a 에서 계산된 r이 0.87이고 모상관계수를 추정하기 위해 0.3보다 크지 않은 95% 신뢰구간이 필요한 경우 다음과 같은 프로세스를 사용할 수 있다. 

``` r
#a)
e_195_b1<-function(n, alpha){
  v=n-2
  f_aa=round(qf(alpha/2, v, v, lower.tail = FALSE), 2)
  L1=round(((1+f_aa)*r+(1-f_aa))/((1+f_aa)+(1-f_aa)*r), 3)
  L2=round(((1+f_aa)*r-(1-f_aa))/((1+f_aa)-(1-f_aa)*r), 3)
  width_CI=L2-L1
  outcome=data.frame(f_aa, L1, L2, width_CI) %>% kbl(caption = "Ex 19.5 (b)") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
  
  return(outcome)
}
```

``` r
e_195_b1(15, 0.05)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.5 (b)
</caption>
<thead>
<tr>
<th style="text-align:right;">
f_aa
</th>
<th style="text-align:right;">
L1
</th>
<th style="text-align:right;">
L2
</th>
<th style="text-align:right;">
width_CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
3.12
</td>
<td style="text-align:right;">
0.644
</td>
<td style="text-align:right;">
0.957
</td>
<td style="text-align:right;">
0.313
</td>
</tr>
</tbody>
</table>

- 먼저 필요한 sample size를 15라고 가정하고 신뢰구간을 구한 결과 신뢰구간의 길이는 0.312이었고, 이는 0.3보다 조금 큰 수치이므로 sample size를 늘려보자.

``` r
e_195_b1(20, 0.05)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.5 (b)
</caption>
<thead>
<tr>
<th style="text-align:right;">
f_aa
</th>
<th style="text-align:right;">
L1
</th>
<th style="text-align:right;">
L2
</th>
<th style="text-align:right;">
width_CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2.6
</td>
<td style="text-align:right;">
0.695
</td>
<td style="text-align:right;">
0.948
</td>
<td style="text-align:right;">
0.253
</td>
</tr>
</tbody>
</table>

- sample size를 20으로 가정하고 신뢰구간을 구한 결과 길이는 0.253이었고, 이는 0.3보다 작은 수치이므로 sample size를 줄여보자.

``` r
e_195_b1(16, 0.05)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.5 (b)
</caption>
<thead>
<tr>
<th style="text-align:right;">
f_aa
</th>
<th style="text-align:right;">
L1
</th>
<th style="text-align:right;">
L2
</th>
<th style="text-align:right;">
width_CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
2.98
</td>
<td style="text-align:right;">
0.658
</td>
<td style="text-align:right;">
0.955
</td>
<td style="text-align:right;">
0.297
</td>
</tr>
</tbody>
</table>

- 이와 같이 계속해서 0.3에 가장 근사하는 sample size를 찾아나간 결과 귀무가설을 기각하기 위해 필요한 최소한의 sample size는 16이 나왔다.<br/><br/>
- 다음은 r=0.87, z=1.3331로 고정된 경우 구하여 보자.

``` r
#b)
e_195_b2<-function(n, r, z){
  sigma_zz=sqrt(1/(n-3))
  z_crit=qnorm(0.025, lower.tail=FALSE)
  L1_F=z-z_crit*sigma_zz
  L2_F=z+z_crit*sigma_zz
  outcome=data.frame(z_crit, L1_F, L2_F) %>% kbl(caption = "Ex 19.5 (b)") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
  
  return(outcome)
}
```

``` r
e_195_b2(15, 0.870, 1.3331)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.5 (b)
</caption>
<thead>
<tr>
<th style="text-align:right;">
z_crit
</th>
<th style="text-align:right;">
L1_F
</th>
<th style="text-align:right;">
L2_F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1.959964
</td>
<td style="text-align:right;">
0.7673071
</td>
<td style="text-align:right;">
1.898893
</td>
</tr>
</tbody>
</table>


- 먼저 필요한 sample size를 15라고 가정하고 신뢰구간을 구한 결과 신뢰구간은 (0.7672,1.8990)이었고, 이를 다시 변환하면 (0.645,0.956)의 값이 나왔다.

![](/study/img/의학통계방법론/ch19/19b-1.png)

- 이 신뢰구간의 길이는 0.312이었고, 이는 0.3보다 조금 큰 수치이므로 sample size를 늘려보자.

``` r
e_195_b2(16, 0.870, 1.3331)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.5 (b)
</caption>
<thead>
<tr>
<th style="text-align:right;">
z_crit
</th>
<th style="text-align:right;">
L1_F
</th>
<th style="text-align:right;">
L2_F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1.959964
</td>
<td style="text-align:right;">
0.7895038
</td>
<td style="text-align:right;">
1.876696
</td>
</tr>
</tbody>
</table>

- sample size를 16라고 가정하고 신뢰구간을 구한 결과 신뢰구간은 (0.7894,1.8768)이었고, 이를 다시 변환하면 (0.658,0.954)의 값이 나왔다.

![](/study/img/의학통계방법론/ch19/19b-2.png)

- 이 신뢰구간의 길이는 0.30이므로 sample size는 16으로 정한다.

### EXAMPLE 19.6

![](/study/img/의학통계방법론/ch19/19-6.png)

- 이 예제에서는 독립인 서로 다른 두 집단의 모상관계수가 같은지에 대해 검정해보겠다.

$$
\begin{aligned}
H_0 &: \rho_1=\rho_2 \\
H_A &: \rho_1 \neq \rho_2
\end{aligned}
$$

> 직접만든 함수로 구하여 보자.

``` r
r1= 0.78 ; r2=0.84
z1=1.0454 ; z2=1.2212
n1=98 ; n2=95
Z=(z1-z2)/sqrt((1/(n1-3))+(1/(n2-3)))
p<-round(pnorm(Z)*2,2)
cat("Z=",round(Z,3),"p-value=",round(p,2),"\nTherefore, do not reject H0.")
```

    ## Z= -1.202 p-value= 0.23 
    ## Therefore, do not reject H0.

> diffcor.two()를 사용하여 구하여 보자.

``` r
library("diffcor")
diffcor.two(0.78, 0.84, 98, 95, alpha = 0.05, cor.names = NULL,alternative = "two.sided")
```

    ##     r1   r2   LL1   UL1   LL2   UL2      z     p Cohen_q
    ## 1 0.78 0.84 0.688 0.847 0.769 0.891 -1.202 0.229  -0.176

- p-value는 모두 유의수준 0.05보다 크게 나타났고 귀무가설을 기각할 수 없다.<br/>
- 따라서 서로 다른 독립된 두 집단의 모상관계수가 다르다고 말할만한 충분한 근거가 없다. <br/>
- 귀무가설이 채택될 경우 공통상관계수를 구할 수 있으며 계산하면 공통상관계수는 0.81이다.

### EXAMPLE 19.7

![](/study/img/의학통계방법론/ch19/19-7.png)

- 이 예제는 두 상관계수를 비교할 때의 검정력을 구하는 문제이다. 

> 직접만든 함수로 구하여 보자.

``` r
z1=1.0454 ; z2=1.2212
sigma_12=0.1463
z_a=qnorm(0.025, lower.tail = FALSE)
z_b=round(((abs(z1-z2))/sigma_12)-z_a, 2)
beta=1-pnorm(z_b)
power.method2 = pnorm(z_b)
data.frame(power.method2) %>% kbl(caption = "Ex 19.7:방법1") %>%  
  kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.7:방법1
</caption>
<thead>
<tr>
<th style="text-align:right;">
power.method2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.2236273
</td>
</tr>
</tbody>
</table>

> power.indep.cor()를 사용하여 구하여 보자.

``` r
library("remotes")
# remotes::install_github('m-Py/cower')
# install_github("m-Py/cower")
library("cower")
e_197=power.indep.cor(r1=0.78, r2=0.84, n1=98, n2=95, sig.level = 0.05, alternative = "two.sided")
power.method1 = e_197$power
data.frame(power.method1) %>% kbl(caption = "Ex 19.7:방법2") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.7:방법2
</caption>
<thead>
<tr>
<th style="text-align:right;">
power.method1
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.2242004
</td>
</tr>
</tbody>
</table>

- 검정통계량 값은 -0.76이고 이를 이용하여 정규분포표에서 값을 구하면 0.78이다. 따라서 검정력은 1-0.78=0.22가 된다.

### EXAMPLE 19.8

![](/study/img/의학통계방법론/ch19/19-8.png)

- 이 예제는 두 상관계수를 비교할 때의 sample size를 구하는 문제이다. 

``` r
z_alpha= round(qnorm(0.05/2, lower.tail = F), 4)
z_beta=round(qnorm(0.10,lower.tail = F), 4)
n_198=2*(((z_alpha+z_beta)/(0.5000))^2)+3
sample.size = ceiling(n_198)
cbind(z_alpha, z_beta, n_198, sample.size) %>% kbl(caption = "Ex 19.8") %>%  
  kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.8
</caption>
<thead>
<tr>
<th style="text-align:right;">
z_alpha
</th>
<th style="text-align:right;">
z_beta
</th>
<th style="text-align:right;">
n_198
</th>
<th style="text-align:right;">
sample.size
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1.96
</td>
<td style="text-align:right;">
1.2816
</td>
<td style="text-align:right;">
87.06376
</td>
<td style="text-align:right;">
88
</td>
</tr>
</tbody>
</table>


- 두 값들의 차이를 이용하여 sample size를 구했고, 그 결과 상관계수 간 0.5의 차이를 발견하기 위해 귀무가설을 기각하기 위한 최소의 필요한 sample size는 88이다.

### EXAMPLE 19.9

![](/study/img/의학통계방법론/ch19/19-9.png)

- 이 예제는 세 개의 상관계수를 비교하는 문제이다. 

$$
\begin{aligned}
H_0 &: \rho_1=\rho_2=\rho_3\\
H_A &: All \ three \ population \ correlation \ coefficients \ are \ not \ equal.
\end{aligned}
$$

``` r
n=c(24,29,32)
r=c(0.52, 0.56, 0.87)

test.three_sample_corr <- function(n,r) {
  z = round(0.5*log((1+r)/(1-r)), 4)
  z_square = round(z^2, 4)
  n_minus_3 = n-3
  n_3_z = n_minus_3*z
  n_3_z_sqaure = n_minus_3*z_square
  test.stat = round(sum(n_3_z_sqaure) - (sum(n_3_z)^2)/sum(n_minus_3), 3)
  df = length(n)-1
  p.value = round(1 - pchisq(test.stat, df), 4)
  result.df = data.frame(test.stat, df, p.value)
  result.df<-result.df %>% kbl(caption = "Ex 19.9") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
  return(result.df)
}

test.three_sample_corr(n,r)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.9
</caption>
<thead>
<tr>
<th style="text-align:right;">
test.stat
</th>
<th style="text-align:right;">
df
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9.478
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.0087
</td>
</tr>
</tbody>
</table>

- 검정통계량 값은 9.478이고 p-value는 0.0087로 유의수준 하에서 귀무가설을 기각하게 된다. <br/>
- 따라서 적어도 하나 이상의 상관계수는 같지 않다고 할 수 있다. <br/><br/>
- 귀무가설이 기각되지 않았다면, common correlation coefficient를 계산하는 것이 적절했을 것이다.

``` r
common.corr <- function(n,r) {
  z = round(0.5*log((1+r)/(1-r)), 4)
  z_square = round(z^2, 4)
  n_minus_3 = n-3
  n_3_z = n_minus_3*z
  n_3_z_sqaure = n_minus_3*z_square
  z.w = sum(n_3_z)/sum(n_minus_3)
  r.w = round((exp(2*z.w)-1) / (exp(2*z.w)+1), 4)
  r.w <- data.frame(r.w)
  r.w <- r.w %>% kbl(caption = "Ex 19.9") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
  
  return(r.w)
}
common.corr(n,r)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.9
</caption>
<thead>
<tr>
<th style="text-align:right;">
r.w
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.7086
</td>
</tr>
</tbody>
</table>

- common correlation coefficient는 0.7086으로 계산되었다.

### EXAMPLE 19.10

![](/study/img/의학통계방법론/ch19/19-10.png)

- 상관계수 변환 시 z-변환이 편향되는 점으로 편향 극복을 위해 수정된 검정통계량 값을 계산하여야 한다.<br/>
- Example 19.9와 동일한 가설을 correction for bias를 이용해 다시 구하여 보겠다.

``` r
n=c(24,29,32)
r=c(0.52, 0.56, 0.87)

test.corr_correction <- function(n,r) {
  z = round(0.5*log((1+r)/(1-r)), 4)
  z_square = round(z^2, 4)
  n_minus_3 = n-3
  n_3_z = n_minus_3*z
  n_3_z_sqaure = n_minus_3*z_square
  z.w = sum(n_3_z)/sum(n_minus_3)
  r.w = round((exp(2*z.w)-1) / (exp(2*z.w)+1), 2)

  test.stat = round(sum(n*t((r- r.w)^2) / (1 - r*r.w)^2), 4)
  df = length(n)-1
  p.value = round(1 - pchisq(test.stat, df), 4)
  result.df = data.frame(test.stat, p.value)
  result.df<-result.df %>% kbl(caption = "Ex 19.10") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
  return(result.df)
}

test.corr_correction(n,r)
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.10
</caption>
<thead>
<tr>
<th style="text-align:right;">
test.stat
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9.5805
</td>
<td style="text-align:right;">
0.0083
</td>
</tr>
</tbody>
</table>

- 계산된 검정통계량은 9.5805, p-value는 0.0083으로 유의수준 0.05보다 작았다.<br/>
- 즉, 유의수준 5%하에 세 개의 모집단 상관 계수가 모두 같지 않다고 말할 충분한 증거가 있다.<br/>
- 이는 Example 19.9의 가설검정 결과와 동일하다.

### EXAMPLE 19.11

![](/study/img/의학통계방법론/ch19/19-11.png)

- 이 예제에서는 앞선 상관계수 검정을 통해 각 상관계수들이 모두 같지 않음을 확인했으므로 다중비교를 진행한다.<br/>
-  Z-변환을 이용하여 Tukey의 다중비교를 진행하였다.

``` r
library("gtools")
z = round(0.5*log((1+r)/(1-r)), 4)
comb<-combinations(3, 2, v = 1:3)

comb <- data.frame(comb)
comb<-comb[order(comb$X2, decreasing = T),]

ex19.11_result = vector()
for (k in 1:3) {
  compar_vec = vector()
  i=comb[k,2]
  j=comb[k,1]
  
  compar=paste0(i," vs. ",j)
  compar_vec = c(compar_vec, "Comparison"=compar)
  
  diff= z[i]-z[j]
  compar_vec = c(compar_vec, "Difference"=diff)
  
  SE = round(sqrt(1/2*(1/(n[i]-3) + 1/(n[j]-3))), 3)
  compar_vec = c(compar_vec, "SE"=SE)
  
  q = round((z[i]-z[j]) / round(sqrt(1/2*(1/(n[i]-3) + 1/(n[j]-3))), 3), 3)
  compar_vec = c(compar_vec, "q"=q)
  compar_vec = c(compar_vec, "critical.value"=3.314)
  
  if (q > 3.314) {
    compar_vec = c(compar_vec, "Conclusion"="Reject H0")
  }
  else {
    compar_vec = c(compar_vec, "Conclusion"="Do not reject H0")
  }
  ex19.11_result<- rbind(ex19.11_result, compar_vec)
}

rownames(ex19.11_result) <- c(rep(" ", 3))

ex19.11_result %>% kbl(caption = "Ex 19.11") %>%  
  kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.11
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
Comparison
</th>
<th style="text-align:left;">
Difference
</th>
<th style="text-align:left;">
SE
</th>
<th style="text-align:left;">
q
</th>
<th style="text-align:left;">
critical.value
</th>
<th style="text-align:left;">
Conclusion
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3 vs. 1
</td>
<td style="text-align:left;">
0.7568
</td>
<td style="text-align:left;">
0.203
</td>
<td style="text-align:left;">
3.728
</td>
<td style="text-align:left;">
3.314
</td>
<td style="text-align:left;">
Reject H0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
3 vs. 2
</td>
<td style="text-align:left;">
0.7003
</td>
<td style="text-align:left;">
0.191
</td>
<td style="text-align:left;">
3.666
</td>
<td style="text-align:left;">
3.314
</td>
<td style="text-align:left;">
Reject H0
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
2 vs. 1
</td>
<td style="text-align:left;">
0.0565
</td>
<td style="text-align:left;">
0.207
</td>
<td style="text-align:left;">
0.273
</td>
<td style="text-align:left;">
3.314
</td>
<td style="text-align:left;">
Do not reject H0
</td>
</tr>
</tbody>
</table>

- 각각의 q 통계량을 3.314와 비교하면 그룹 3과 그룹1,2는 상관계수가 같다는 귀무가설을 기각했지만, 그룹 1과 그룹2는 귀무가설을 기각하지 못했다. <br/>
- 따라서 그룹 1과 그룹 2의 상관계수는 같으나 그룹 3의 상관계수는 다르다고 할 수 있다.

### EXAMPLE 19.12

![](/study/img/의학통계방법론/ch19/19-12.png)

``` r
#데이터셋
ex19_12 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Student
</th>
<th style="text-align:right;">
X
</th>
<th style="text-align:right;">
Y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
57
</td>
<td style="text-align:right;">
83
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
37
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:right;">
41
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
78
</td>
<td style="text-align:right;">
84
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
53
</td>
<td style="text-align:right;">
56
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
85
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
86
</td>
<td style="text-align:right;">
77
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
98
</td>
<td style="text-align:right;">
87
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
59
</td>
<td style="text-align:right;">
70
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
71
</td>
<td style="text-align:right;">
59
</td>
</tr>
</tbody>
</table>

- n이 10 이상이고 순위상관계수가 0.9 이하이면 Fisher’s z-변환은 Spearman의 상관계수에도 사용될 수 있다. 

``` r
ex19_12.result <-cor.test(ex19_12$X, ex19_12$Y, method="spearman")
ex19_12.result
```

    ## 
    ##  Spearman's rank correlation rho
    ## 
    ## data:  ex19_12$X and ex19_12$Y
    ## S = 72, p-value = 0.09579
    ## alternative hypothesis: true rho is not equal to 0
    ## sample estimates:
    ##       rho 
    ## 0.5636364

``` r
ex19_12.result_table <- cbind("statistic"=ex19_12.result$statistic, "r"=round(ex19_12.result$estimate, 3),
      "p.value"=round(ex19_12.result$p.value, 3))
rownames(ex19_12.result_table)=c(" ")

ex19_12.result_table %>% kbl(caption = "Ex 19.12") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.12
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
r
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:right;">
0.564
</td>
<td style="text-align:right;">
0.096
</td>
</tr>
</tbody>
</table>

- 계산된 검정통계량 값은 0.564, p-value는 0.096으로 유의수준 0.05보다 크므로 귀무가설을 기각할 수 없다.<br/>
- 즉, 순위상관계수는 0이라고 말할 수 있으며, 수학시험 점수와 생물시험 점수 간 상관관계가 있다는 근거가 충분하지 않다고 말할 수 있다.

### EXAMPLE 19.13

![](/study/img/의학통계방법론/ch19/19-13.png)

``` r
#데이터셋
ex19_13 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Student
</th>
<th style="text-align:right;">
X
</th>
<th style="text-align:right;">
Y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.4
</td>
<td style="text-align:right;">
7.4
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
7.6
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
11.1
</td>
<td style="text-align:right;">
7.9
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
10.2
</td>
<td style="text-align:right;">
7.2
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
10.3
</td>
<td style="text-align:right;">
7.4
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
10.2
</td>
<td style="text-align:right;">
7.1
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
10.7
</td>
<td style="text-align:right;">
7.4
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
10.5
</td>
<td style="text-align:right;">
7.2
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
10.8
</td>
<td style="text-align:right;">
7.8
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
11.2
</td>
<td style="text-align:right;">
7.7
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
10.6
</td>
<td style="text-align:right;">
7.8
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
11.4
</td>
<td style="text-align:right;">
8.3
</td>
</tr>
</tbody>
</table>

- 이 예제에서는 Example 19.1 데이터를 가지고 특정 종의 새에 대한 날개와 꼬리 사이에 순위 상관성이 존재하는지 확인하기 위해 검정할 것이다.

$$
\begin{aligned}
H_0 &: \rho_s=0 \\
H_A &: \rho_s \neq 0
\end{aligned}
$$

``` r
cor.test(ex19_13$X,ex19_13$Y,method = "spearman", exact = F)
```

    ## 
    ##  Spearman's rank correlation rho
    ## 
    ## data:  ex19_13$X and ex19_13$Y
    ## S = 42.59, p-value = 0.0004467
    ## alternative hypothesis: true rho is not equal to 0
    ## sample estimates:
    ##       rho 
    ## 0.8510852

- 둘 사이에 순위 상관계수는 0.851이며 test 결과 p-value가 0.0004로 유의수준 0.05 보다 작기 때문에 귀무가설을 기각한다.<br/>
- 즉, 새의 날개와 꼬리 간에 순위 상관 관계가 존재한다고 할 수 있다.

### EXAMPLE 19.14

![](/study/img/의학통계방법론/ch19/19-14.png)

``` r
#데이터셋
ex19_14 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:left;">
Factor
</th>
<th style="text-align:right;">
Species1
</th>
<th style="text-align:right;">
Species2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
E
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
G
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
H
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
4
</td>
</tr>
</tbody>
</table>

$$
\begin{aligned}
H_0 &: The \ same \ ecological \ factors \ are \ most \ important \ to \ both \ species. \\
H_A &: The \ same \ ecological \ factors \ are \ not \ most \ important \ to \ both \ species.
\end{aligned}
$$

- 가중 순위 상관계수를 구하기 위해선 savage score을 사용한다.

``` r
j.inverse <- ex19_14$Species1^(-1)
savage.number1 = vector()
savage.number2 = vector()
for (k in 1:8) {
  S1 = round(sum(j.inverse[ex19_14$Species1[k]:8]), 3)
  savage.number1 = c(savage.number1, S1)
  
  S2 = round(sum(j.inverse[ex19_14$Species2[k]:8]), 3)
  savage.number2 = c(savage.number2, S2)
}

ex19_14.result <- cbind(ex19_14, savage.number1, savage.number2,
                        "(S1)(S2)"=round(savage.number1*savage.number2, 3))

ex19_14.result %>% kbl(caption = "Ex 19.14") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.14
</caption>
<thead>
<tr>
<th style="text-align:left;">
Factor
</th>
<th style="text-align:right;">
Species1
</th>
<th style="text-align:right;">
Species2
</th>
<th style="text-align:right;">
savage.number1
</th>
<th style="text-align:right;">
savage.number2
</th>
<th style="text-align:right;">
(S1)(S2)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2.718
</td>
<td style="text-align:right;">
2.718
</td>
<td style="text-align:right;">
7.388
</td>
</tr>
<tr>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1.718
</td>
<td style="text-align:right;">
1.718
</td>
<td style="text-align:right;">
2.952
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1.218
</td>
<td style="text-align:right;">
1.218
</td>
<td style="text-align:right;">
1.484
</td>
</tr>
<tr>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.885
</td>
<td style="text-align:right;">
0.268
</td>
<td style="text-align:right;">
0.237
</td>
</tr>
<tr>
<td style="text-align:left;">
E
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.635
</td>
<td style="text-align:right;">
0.125
</td>
<td style="text-align:right;">
0.079
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.435
</td>
<td style="text-align:right;">
0.435
</td>
<td style="text-align:right;">
0.189
</td>
</tr>
<tr>
<td style="text-align:left;">
G
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.268
</td>
<td style="text-align:right;">
0.635
</td>
<td style="text-align:right;">
0.170
</td>
</tr>
<tr>
<td style="text-align:left;">
H
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.125
</td>
<td style="text-align:right;">
0.885
</td>
<td style="text-align:right;">
0.111
</td>
</tr>
</tbody>
</table>

``` r
summation = sum(round(savage.number1*savage.number2, 3))
n = length(ex19_14$Factor)
r.T = round((summation-n) / (n-savage.number1[1]), 3)
cbind(n, r.T) %>% kbl(caption = "Ex 19.14") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.14
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
r.T
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.873
</td>
</tr>
</tbody>
</table>

- Top down correlation 분석 결과, 상관계수는 0.873으로 계산되었다.

``` r
cor.test(savage.number1,savage.number2)
```

    ## 
    ##  Pearson's product-moment correlation
    ## 
    ## data:  savage.number1 and savage.number2
    ## t = 4.3616, df = 6, p-value = 0.004762
    ## alternative hypothesis: true correlation is not equal to 0
    ## 95 percent confidence interval:
    ##  0.4337146 0.9765680
    ## sample estimates:
    ##       cor 
    ## 0.8719087

- 검정 결과 상관계수는 0.8719087이며 이에 대한 검정 결과 p-value=0.004762 이므로 0.05보다 작기 때문에 동일한 생태적 요인이 두 종 모두에게 가장 중요한 것은 아니라는 결론을 내릴 수 있다.

### EXAMPLE 19.15

![](/study/img/의학통계방법론/ch19/19-15.png)

``` r
#데이터셋
ex19_15 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Case
</th>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:right;">
Insect
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">

-   </td>
    <td style="text-align:right;">
    1
    </td>
    </tr>
    <tr>
    <td style="text-align:right;">
    2
    </td>
    <td style="text-align:left;">

    -   </td>
        <td style="text-align:right;">
        1
        </td>
        </tr>
        <tr>
        <td style="text-align:right;">
        3
        </td>
        <td style="text-align:left;">

        -   </td>
            <td style="text-align:right;">
            0
            </td>
            </tr>
            <tr>
            <td style="text-align:right;">
            4
            </td>
            <td style="text-align:left;">

            -   </td>
                <td style="text-align:right;">
                1
                </td>
                </tr>
                <tr>
                <td style="text-align:right;">
                5
                </td>
                <td style="text-align:left;">

                -   </td>
                    <td style="text-align:right;">
                    1
                    </td>
                    </tr>
                    <tr>
                    <td style="text-align:right;">
                    6
                    </td>
                    <td style="text-align:left;">

                    -   </td>
                        <td style="text-align:right;">
                        1
                        </td>
                        </tr>
                        <tr>
                        <td style="text-align:right;">
                        7
                        </td>
                        <td style="text-align:left;">

                        -   </td>
                            <td style="text-align:right;">
                            0
                            </td>
                            </tr>
                            <tr>
                            <td style="text-align:right;">
                            8
                            </td>
                            <td style="text-align:left;">

                            -   </td>
                                <td style="text-align:right;">
                                1
                                </td>
                                </tr>
                                <tr>
                                <td style="text-align:right;">
                                9
                                </td>
                                <td style="text-align:left;">

                                -   </td>
                                    <td style="text-align:right;">
                                    1
                                    </td>
                                    </tr>
                                    <tr>
                                    <td style="text-align:right;">
                                    10
                                    </td>
                                    <td style="text-align:left;">

                                    -   </td>
                                        <td style="text-align:right;">
                                        0
                                        </td>
                                        </tr>
                                        <tr>
                                        <td style="text-align:right;">
                                        11
                                        </td>
                                        <td style="text-align:left;">

                                        -   </td>
                                            <td style="text-align:right;">
                                            1
                                            </td>
                                            </tr>
                                            <tr>
                                            <td style="text-align:right;">
                                            12
                                            </td>
                                            <td style="text-align:left;">

                                            -   </td>
                                                <td style="text-align:right;">
                                                0
                                                </td>
                                                </tr>
                                                <tr>
                                                <td style="text-align:right;">
                                                13
                                                </td>
                                                <td style="text-align:left;">

                                                -   </td>
                                                    <td style="text-align:right;">
                                                    1
                                                    </td>
                                                    </tr>
                                                    <tr>
                                                    <td style="text-align:right;">
                                                    14
                                                    </td>
                                                    <td style="text-align:left;">

                                                    -   </td>
                                                        <td style="text-align:right;">
                                                        1
                                                        </td>
                                                        </tr>
                                                        </tbody>
                                                        </table>

- 해당 데이터는 두 개의 이항형 변수, 특정 곤충의 유무와 식물 유병의 유무에 대하여 기록한 데이터이다.<br/>
- phi 계수, Yule의 계수, 그리고 Ives and Gibbons의 계수로 상관관계를 알아보겠다.

``` r
library("psych")
cross.table<-table(ex19_15$Disease, ex19_15$Insect)

phi.coefficient <- phi(cross.table, digits = 2)
Yule.coefficient <- Yule(cross.table,Y=FALSE)
r.n = round(((cross.table[2,2] + cross.table[1,1]) - (cross.table[1,2] + cross.table[2,1])) / 
  ((cross.table[2,2] + cross.table[1,1]) + (cross.table[1,2] + cross.table[2,1])), 2)

ex19_15.result <- cbind(phi.coefficient, Yule.coefficient, r.n)

ex19_15.result %>% kbl(caption = "Ex 19.15") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.15
</caption>
<thead>
<tr>
<th style="text-align:right;">
phi.coefficient
</th>
<th style="text-align:right;">
Yule.coefficient
</th>
<th style="text-align:right;">
r.n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.43
</td>
</tr>
</tbody>
</table>

-  phi의 계수의 경우 0.55, Yule의 계수의 경우 0.97 (almost 1), 그리고 Ives and Gibbons의 계수의 경우 약 0.43의 값을 가진다.

### EXAMPLE 19.16

![](/study/img/의학통계방법론/ch19/19-16.png)

``` r
#데이터셋
ex19_16 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
X
</th>
<th style="text-align:right;">
Y
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8.8
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8.4
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7.9
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8.7
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9.1
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
9.6
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.9
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.0
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11.1
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.6
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8.7
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.4
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.5
</td>
</tr>
</tbody>
</table>

- 예제 8.1은 변수 X가 약의 종류 2가지로 이항형이고, 변수 Y는 피가 응고되는 시간으로 연속형으로 하나의 변수가 이항형인 데이터이다.
- Example 8.1 데이터를 사용하여 피가 응고되는 시간과 약의 종류 간의 상관성을 알아보도록 하겠다.

$$
\begin{aligned}
H_0 &: \rho_pb=0 \ (There \ is \ no \ correlation \ between \ blood-clotting \ time \ and \ drug.)\\
H_A &: \rho_pb \neq 0 \ (There \ is \ correlation \ between \ blood-clotting \ time \ and \ drug.)
\end{aligned}
$$

``` r
library("ltm")
r.pb = round(biserial.cor(ex19_16$Y,ex19_16$X,level=2), 4)
r.pb_square = round(r.pb^2, 4)

ex19_16.result <- cor.test(ex19_16$Y,ex19_16$X)
ex19_16.result
```

    ## 
    ##  Pearson's product-moment correlation
    ## 
    ## data:  ex19_16$Y and ex19_16$X
    ## t = 2.4765, df = 11, p-value = 0.03076
    ## alternative hypothesis: true correlation is not equal to 0
    ## 95 percent confidence interval:
    ##  0.07058429 0.86434926
    ## sample estimates:
    ##       cor 
    ## 0.5983011

``` r
ex19_16.resultdf <- cbind(r.pb, r.pb_square,
                          "statistic"=round(ex19_16.result$statistic, 3),
                          "p.value"=round(ex19_16.result$p.value, 3)
                          )
rownames(ex19_16.resultdf) = c(" ")
ex19_16.resultdf %>% kbl(caption = "Ex 19.16") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.16
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
r.pb
</th>
<th style="text-align:right;">
r.pb_square
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
0.5983
</td>
<td style="text-align:right;">
0.358
</td>
<td style="text-align:right;">
2.476
</td>
<td style="text-align:right;">
0.031
</td>
</tr>
</tbody>
</table>

- 계산된 Point-Biserial 상관계수는 0.5983이다. <br/>
- 그리고 검정통계량은 2.476이며, p-value는 0.031으로 유의수준 5%하에 귀무가설을 기각한다.<br/>
- 즉, 혈액 응고 시간과 약물 사이에는 상관관계가 존재한다는 충분한 증거가 있다.

### EXAMPLE 19.17

![](/study/img/의학통계방법론/ch19/19-17.png)

``` r
#데이터셋
ex19_17 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Group
</th>
<th style="text-align:right;">
One
</th>
<th style="text-align:right;">
Other
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
70.4
</td>
<td style="text-align:right;">
71.3
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
68.2
</td>
<td style="text-align:right;">
67.4
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
77.3
</td>
<td style="text-align:right;">
75.2
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
61.2
</td>
<td style="text-align:right;">
66.7
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
72.3
</td>
<td style="text-align:right;">
74.2
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
74.1
</td>
<td style="text-align:right;">
72.9
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
71.1
</td>
<td style="text-align:right;">
69.5
</td>
</tr>
</tbody>
</table>

- 해당 데이터는 쌍둥이들의 체중에 대해 기록한 데이터이다.<br/>
- 쌍둥이들의 체중 사이에 급내 상관계수에 대해 알아보고자 한다.<br/>
- 급내상관계수 과정에 대한 가정으로 이변량 정규 분포로 부터 랜덤하게 추출되어야 하며, 모집단의 분산이 동일해야 한다.

> 정규성 검정

``` r
shapiro.test(ex19_17$One)
```

    ## 
    ##  Shapiro-Wilk normality test
    ## 
    ## data:  ex19_17$One
    ## W = 0.94626, p-value = 0.6956

``` r
shapiro.test(ex19_17$Other)
```

    ## 
    ##  Shapiro-Wilk normality test
    ## 
    ## data:  ex19_17$Other
    ## W = 0.94088, p-value = 0.6466

- 정규성 검정결과, p-value가 각 그룹에서 0.6956, 0.6466으로, 두 그룹모두 정규성 가정을 만족하였다.

> 등분산성 검정

``` r
bartlett.test(ex19_17[,2:3])
```

    ## 
    ##  Bartlett test of homogeneity of variances
    ## 
    ## data:  ex19_17[, 2:3]
    ## Bartlett's K-squared = 0.99636, df = 1, p-value = 0.3182

- 분산 검정결과 p-value가 0.3182으로 유의수준 0.05보다 컸다. 그러므로 등분산 가정도 만족하였다.

``` r
library("irr")
ex19_17.result <- icc(ex19_17[,2:3], unit="single",r0=0)
ex19_17.resultdf<-cbind("r1"=round(ex19_17.result$value, 3),
                        "F.value"=round(ex19_17.result$Fvalue, 1),
                        "p.value"=round(ex19_17.result$p.value, 4))
ex19_17.resultdf %>% kbl(caption = "Ex 19.17") %>%  
    kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.17
</caption>
<thead>
<tr>
<th style="text-align:right;">
r1
</th>
<th style="text-align:right;">
F.value
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.827
</td>
<td style="text-align:right;">
10.6
</td>
<td style="text-align:right;">
0.0033
</td>
</tr>
</tbody>
</table>

- 일곱 쌍둥이 간 체중의 급내 상관관수는 0.827이며, <br/>
- 급내 상관관계를 확인하기 위한 검정 결과 F값=10.6, p-value= 0.00325로 유의수준 5%하에 귀무가설을 기각한다. <br/>
- 즉, 일곱 쌍둥이 간 체중에 대해 급내 상관관계가 있다고 할 수 있다.

### EXAMPLE 19.18

![](/study/img/의학통계방법론/ch19/19-18-1.png)

``` r
#데이터셋
ex19_18 %>%
  kbl(caption = "Dataset",escape=F) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
Dataset
</caption>
<thead>
<tr>
<th style="text-align:right;">
Group
</th>
<th style="text-align:right;">
A
</th>
<th style="text-align:right;">
B
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.22
</td>
<td style="text-align:right;">
0.21
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.26
</td>
<td style="text-align:right;">
0.23
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0.30
</td>
<td style="text-align:right;">
0.27
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.33
</td>
<td style="text-align:right;">
0.27
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0.36
</td>
<td style="text-align:right;">
0.31
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0.39
</td>
<td style="text-align:right;">
0.33
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.41
</td>
<td style="text-align:right;">
0.37
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0.44
</td>
<td style="text-align:right;">
0.38
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
0.47
</td>
<td style="text-align:right;">
0.40
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
0.51
</td>
<td style="text-align:right;">
0.43
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
0.55
</td>
<td style="text-align:right;">
0.47
</td>
</tr>
</tbody>
</table>

- 해당 데이터는 두 개의 다른 원자 흡수 분광 광도계를 사용하여 뇌 조직의 납 농도 분석한 데이터이다.<br/>
- 이 예제의 데이터를 사용하여 일치 상관계수를 구해보도록 한다. <br/>
- 일치 상관계수는 데이턴의 일치도 혹은 재현성을 평가하기 위한 지표이다.

``` r
n<-length(ex19_18$A)
mean.A <- round(mean(ex19_18$A),3)
mean.B <- round(mean(ex19_18$B),3)
sum.A <- sum(ex19_18$A)
sum.B <- sum(ex19_18$B)
sum.AB <- sum(ex19_18$A*ex19_18$B)
sum.A2 <- sum(ex19_18$A^2)
sum.B2 <- sum(ex19_18$B^2)

ssA <- round(sum((ex19_18$A-mean.A)^2),5)
ssB <- round(sum((ex19_18$B-mean.B)^2),5)
ssAB <- sum((ex19_18$A-mean.A)*(ex19_18$B-mean.B))
r.c <- (2*ssAB) / (ssA+ssB+n*(mean.A-mean.B)^2)
r2.c <- r.c^2
r0 = ssAB / sqrt(ssA*ssB)
r02 = r0^2
U = (sqrt(n)*((mean.A-mean.B)^2)) / sqrt(ssA*ssB)

cbind(r.c, r2.c, r0, U) %>% kbl(caption ="Ex 19.18") %>%  
  kable_classic(full_width = F, html_font = "Cambria")
```

<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Ex 19.18
</caption>
<thead>
<tr>
<th style="text-align:right;">
r.c
</th>
<th style="text-align:right;">
r2.c
</th>
<th style="text-align:right;">
r0
</th>
<th style="text-align:right;">
U
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.8373719
</td>
<td style="text-align:right;">
0.7011917
</td>
<td style="text-align:right;">
0.9937578
</td>
<td style="text-align:right;">
0.0991292
</td>
</tr>
</tbody>
</table>

``` r
CCC(ex19_18$A, ex19_18$B, ci="z-transform", conf.level = 0.95)
```

    ## $rho.c
    ##         est    lwr.ci    upr.ci
    ## 1 0.8337058 0.6470369 0.9260831
    ## 
    ## $s.shift
    ## [1] 0.809665
    ## 
    ## $l.shift
    ## [1] -0.5826083
    ## 
    ## $C.b
    ## [1] 0.8388642
    ## 
    ## $blalt
    ##     mean delta
    ## 1  0.215  0.01
    ## 2  0.245  0.03
    ## 3  0.285  0.03
    ## 4  0.300  0.06
    ## 5  0.335  0.05
    ## 6  0.360  0.06
    ## 7  0.390  0.04
    ## 8  0.410  0.06
    ## 9  0.435  0.07
    ## 10 0.470  0.08
    ## 11 0.510  0.08

- 일치 상관계수는 데이터의 일치도 또는 재현성을 평가하기 위한 계수로 -1에서 1사이의 값을 가지고 절대값이 Pearson 상관계수보다 클 수 없으며, Pearson 상관계수가 0일 경우 일치 상관계수 또한 0이 나온다.<br/>
- 변수 A와 B에 대한 상관계수는 0.99로 0이 아님을 확인할 수 있고, 둘의 일치 상관계수는 0.8337이다.

</div>
</details>

<br/>

# SAS 프로그램 결과

<details>
<summary>
SAS 접기/펼치기 버튼
</summary>
<div markdown="1">

## 19장



</div>
</details>

<br/>

<br/>

<font color='#fb8072'>교재: Biostatistical Analysis (5th Edition) by Jerrold H. Zar</font><br/>

<font color='#fb8072'> **이 글은 22학년도 1학기 의학통계방법론 과제 자료들을 정리한 글 입니다.** </font>